#!/bin/bash
set -e

# Source ZITADEL credentials generated by the bootstrap container.
# Docker Compose env_file is resolved at creation time; on the first
# "docker compose up" .env.zitadel doesn't exist yet, so the vars will
# be missing. This sources them from the shared zitadel-data volume.
if [ -f /home/app/zitadel-data/env.zitadel ]; then
  echo "==> Loading ZITADEL config from zitadel-data volume..."
  set -a
  source /home/app/zitadel-data/env.zitadel
  set +a
fi

echo "==> Running Alembic migrations..."
python -m alembic upgrade head

echo "==> Ensuring MinIO bucket exists..."
python -c "
import boto3, os
from botocore.exceptions import ClientError
s3 = boto3.client('s3',
    endpoint_url=os.environ.get('S3_ENDPOINT_URL', 'http://minio:9000'),
    aws_access_key_id=os.environ.get('S3_ACCESS_KEY_ID', 'minioadmin'),
    aws_secret_access_key=os.environ.get('S3_SECRET_ACCESS_KEY', 'minioadmin'),
    region_name='us-east-1')
bucket = os.environ.get('S3_BUCKET', 'voter-imports')
try:
    s3.head_bucket(Bucket=bucket)
    print(f'Bucket {bucket} already exists')
except ClientError:
    s3.create_bucket(Bucket=bucket)
    print(f'Created bucket {bucket}')
"

SSL_ARGS=""
if [ "${DISABLE_TLS}" = "true" ]; then
  echo "    (TLS disabled via DISABLE_TLS env var)"
elif [ -f /home/app/certs/dev.tailb56d83.ts.net.crt ]; then
  echo "    (TLS enabled via Tailscale certs)"
  SSL_ARGS="--ssl-certfile /home/app/certs/dev.tailb56d83.ts.net.crt --ssl-keyfile /home/app/certs/dev.tailb56d83.ts.net.key"
fi

UVICORN_WORKERS="${UVICORN_WORKERS:-1}"
if [ "$UVICORN_WORKERS" -gt 1 ]; then
  echo "==> Starting uvicorn with $UVICORN_WORKERS workers (no hot-reload)..."
  exec python -m uvicorn main:app --host 0.0.0.0 --port 8000 --workers "$UVICORN_WORKERS" --log-level info $SSL_ARGS
else
  echo "==> Starting uvicorn with hot-reload..."
  exec python -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload --log-level info $SSL_ARGS
fi
