/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CampaignsCampaignIdRouteImport } from './routes/campaigns/$campaignId'
import { Route as CampaignsCampaignIdVolunteersRouteImport } from './routes/campaigns/$campaignId/volunteers'
import { Route as CampaignsCampaignIdPhoneBankingRouteImport } from './routes/campaigns/$campaignId/phone-banking'
import { Route as CampaignsCampaignIdDashboardRouteImport } from './routes/campaigns/$campaignId/dashboard'
import { Route as CampaignsCampaignIdCanvassingRouteImport } from './routes/campaigns/$campaignId/canvassing'
import { Route as CampaignsCampaignIdVotersIndexRouteImport } from './routes/campaigns/$campaignId/voters/index'
import { Route as CampaignsCampaignIdVotersVoterIdRouteImport } from './routes/campaigns/$campaignId/voters/$voterId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsCampaignIdRoute = CampaignsCampaignIdRouteImport.update({
  id: '/campaigns/$campaignId',
  path: '/campaigns/$campaignId',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsCampaignIdVolunteersRoute =
  CampaignsCampaignIdVolunteersRouteImport.update({
    id: '/volunteers',
    path: '/volunteers',
    getParentRoute: () => CampaignsCampaignIdRoute,
  } as any)
const CampaignsCampaignIdPhoneBankingRoute =
  CampaignsCampaignIdPhoneBankingRouteImport.update({
    id: '/phone-banking',
    path: '/phone-banking',
    getParentRoute: () => CampaignsCampaignIdRoute,
  } as any)
const CampaignsCampaignIdDashboardRoute =
  CampaignsCampaignIdDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => CampaignsCampaignIdRoute,
  } as any)
const CampaignsCampaignIdCanvassingRoute =
  CampaignsCampaignIdCanvassingRouteImport.update({
    id: '/canvassing',
    path: '/canvassing',
    getParentRoute: () => CampaignsCampaignIdRoute,
  } as any)
const CampaignsCampaignIdVotersIndexRoute =
  CampaignsCampaignIdVotersIndexRouteImport.update({
    id: '/voters/',
    path: '/voters/',
    getParentRoute: () => CampaignsCampaignIdRoute,
  } as any)
const CampaignsCampaignIdVotersVoterIdRoute =
  CampaignsCampaignIdVotersVoterIdRouteImport.update({
    id: '/voters/$voterId',
    path: '/voters/$voterId',
    getParentRoute: () => CampaignsCampaignIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRouteWithChildren
  '/campaigns/$campaignId/canvassing': typeof CampaignsCampaignIdCanvassingRoute
  '/campaigns/$campaignId/dashboard': typeof CampaignsCampaignIdDashboardRoute
  '/campaigns/$campaignId/phone-banking': typeof CampaignsCampaignIdPhoneBankingRoute
  '/campaigns/$campaignId/volunteers': typeof CampaignsCampaignIdVolunteersRoute
  '/campaigns/$campaignId/voters/$voterId': typeof CampaignsCampaignIdVotersVoterIdRoute
  '/campaigns/$campaignId/voters/': typeof CampaignsCampaignIdVotersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRouteWithChildren
  '/campaigns/$campaignId/canvassing': typeof CampaignsCampaignIdCanvassingRoute
  '/campaigns/$campaignId/dashboard': typeof CampaignsCampaignIdDashboardRoute
  '/campaigns/$campaignId/phone-banking': typeof CampaignsCampaignIdPhoneBankingRoute
  '/campaigns/$campaignId/volunteers': typeof CampaignsCampaignIdVolunteersRoute
  '/campaigns/$campaignId/voters/$voterId': typeof CampaignsCampaignIdVotersVoterIdRoute
  '/campaigns/$campaignId/voters': typeof CampaignsCampaignIdVotersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRouteWithChildren
  '/campaigns/$campaignId/canvassing': typeof CampaignsCampaignIdCanvassingRoute
  '/campaigns/$campaignId/dashboard': typeof CampaignsCampaignIdDashboardRoute
  '/campaigns/$campaignId/phone-banking': typeof CampaignsCampaignIdPhoneBankingRoute
  '/campaigns/$campaignId/volunteers': typeof CampaignsCampaignIdVolunteersRoute
  '/campaigns/$campaignId/voters/$voterId': typeof CampaignsCampaignIdVotersVoterIdRoute
  '/campaigns/$campaignId/voters/': typeof CampaignsCampaignIdVotersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/login'
    | '/campaigns/$campaignId'
    | '/campaigns/$campaignId/canvassing'
    | '/campaigns/$campaignId/dashboard'
    | '/campaigns/$campaignId/phone-banking'
    | '/campaigns/$campaignId/volunteers'
    | '/campaigns/$campaignId/voters/$voterId'
    | '/campaigns/$campaignId/voters/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callback'
    | '/login'
    | '/campaigns/$campaignId'
    | '/campaigns/$campaignId/canvassing'
    | '/campaigns/$campaignId/dashboard'
    | '/campaigns/$campaignId/phone-banking'
    | '/campaigns/$campaignId/volunteers'
    | '/campaigns/$campaignId/voters/$voterId'
    | '/campaigns/$campaignId/voters'
  id:
    | '__root__'
    | '/'
    | '/callback'
    | '/login'
    | '/campaigns/$campaignId'
    | '/campaigns/$campaignId/canvassing'
    | '/campaigns/$campaignId/dashboard'
    | '/campaigns/$campaignId/phone-banking'
    | '/campaigns/$campaignId/volunteers'
    | '/campaigns/$campaignId/voters/$voterId'
    | '/campaigns/$campaignId/voters/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CallbackRoute: typeof CallbackRoute
  LoginRoute: typeof LoginRoute
  CampaignsCampaignIdRoute: typeof CampaignsCampaignIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignId': {
      id: '/campaigns/$campaignId'
      path: '/campaigns/$campaignId'
      fullPath: '/campaigns/$campaignId'
      preLoaderRoute: typeof CampaignsCampaignIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignId/volunteers': {
      id: '/campaigns/$campaignId/volunteers'
      path: '/volunteers'
      fullPath: '/campaigns/$campaignId/volunteers'
      preLoaderRoute: typeof CampaignsCampaignIdVolunteersRouteImport
      parentRoute: typeof CampaignsCampaignIdRoute
    }
    '/campaigns/$campaignId/phone-banking': {
      id: '/campaigns/$campaignId/phone-banking'
      path: '/phone-banking'
      fullPath: '/campaigns/$campaignId/phone-banking'
      preLoaderRoute: typeof CampaignsCampaignIdPhoneBankingRouteImport
      parentRoute: typeof CampaignsCampaignIdRoute
    }
    '/campaigns/$campaignId/dashboard': {
      id: '/campaigns/$campaignId/dashboard'
      path: '/dashboard'
      fullPath: '/campaigns/$campaignId/dashboard'
      preLoaderRoute: typeof CampaignsCampaignIdDashboardRouteImport
      parentRoute: typeof CampaignsCampaignIdRoute
    }
    '/campaigns/$campaignId/canvassing': {
      id: '/campaigns/$campaignId/canvassing'
      path: '/canvassing'
      fullPath: '/campaigns/$campaignId/canvassing'
      preLoaderRoute: typeof CampaignsCampaignIdCanvassingRouteImport
      parentRoute: typeof CampaignsCampaignIdRoute
    }
    '/campaigns/$campaignId/voters/': {
      id: '/campaigns/$campaignId/voters/'
      path: '/voters'
      fullPath: '/campaigns/$campaignId/voters/'
      preLoaderRoute: typeof CampaignsCampaignIdVotersIndexRouteImport
      parentRoute: typeof CampaignsCampaignIdRoute
    }
    '/campaigns/$campaignId/voters/$voterId': {
      id: '/campaigns/$campaignId/voters/$voterId'
      path: '/voters/$voterId'
      fullPath: '/campaigns/$campaignId/voters/$voterId'
      preLoaderRoute: typeof CampaignsCampaignIdVotersVoterIdRouteImport
      parentRoute: typeof CampaignsCampaignIdRoute
    }
  }
}

interface CampaignsCampaignIdRouteChildren {
  CampaignsCampaignIdCanvassingRoute: typeof CampaignsCampaignIdCanvassingRoute
  CampaignsCampaignIdDashboardRoute: typeof CampaignsCampaignIdDashboardRoute
  CampaignsCampaignIdPhoneBankingRoute: typeof CampaignsCampaignIdPhoneBankingRoute
  CampaignsCampaignIdVolunteersRoute: typeof CampaignsCampaignIdVolunteersRoute
  CampaignsCampaignIdVotersVoterIdRoute: typeof CampaignsCampaignIdVotersVoterIdRoute
  CampaignsCampaignIdVotersIndexRoute: typeof CampaignsCampaignIdVotersIndexRoute
}

const CampaignsCampaignIdRouteChildren: CampaignsCampaignIdRouteChildren = {
  CampaignsCampaignIdCanvassingRoute: CampaignsCampaignIdCanvassingRoute,
  CampaignsCampaignIdDashboardRoute: CampaignsCampaignIdDashboardRoute,
  CampaignsCampaignIdPhoneBankingRoute: CampaignsCampaignIdPhoneBankingRoute,
  CampaignsCampaignIdVolunteersRoute: CampaignsCampaignIdVolunteersRoute,
  CampaignsCampaignIdVotersVoterIdRoute: CampaignsCampaignIdVotersVoterIdRoute,
  CampaignsCampaignIdVotersIndexRoute: CampaignsCampaignIdVotersIndexRoute,
}

const CampaignsCampaignIdRouteWithChildren =
  CampaignsCampaignIdRoute._addFileChildren(CampaignsCampaignIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CallbackRoute: CallbackRoute,
  LoginRoute: LoginRoute,
  CampaignsCampaignIdRoute: CampaignsCampaignIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
