/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CampaignsNewRouteImport } from './routes/campaigns/new'
import { Route as CampaignsCampaignIdRouteImport } from './routes/campaigns/$campaignId'
import { Route as CampaignsCampaignIdVolunteersRouteImport } from './routes/campaigns/$campaignId/volunteers'
import { Route as CampaignsCampaignIdSurveysRouteImport } from './routes/campaigns/$campaignId/surveys'
import { Route as CampaignsCampaignIdPhoneBankingRouteImport } from './routes/campaigns/$campaignId/phone-banking'
import { Route as CampaignsCampaignIdDashboardRouteImport } from './routes/campaigns/$campaignId/dashboard'
import { Route as CampaignsCampaignIdCanvassingRouteImport } from './routes/campaigns/$campaignId/canvassing'
import { Route as CampaignsCampaignIdVotersIndexRouteImport } from './routes/campaigns/$campaignId/voters/index'
import { Route as CampaignsCampaignIdSurveysIndexRouteImport } from './routes/campaigns/$campaignId/surveys/index'
import { Route as CampaignsCampaignIdCanvassingIndexRouteImport } from './routes/campaigns/$campaignId/canvassing/index'
import { Route as CampaignsCampaignIdVotersVoterIdRouteImport } from './routes/campaigns/$campaignId/voters/$voterId'
import { Route as CampaignsCampaignIdCanvassingWalkListsWalkListIdRouteImport } from './routes/campaigns/$campaignId/canvassing/walk-lists/$walkListId'
import { Route as CampaignsCampaignIdCanvassingTurfsNewRouteImport } from './routes/campaigns/$campaignId/canvassing/turfs/new'
import { Route as CampaignsCampaignIdCanvassingTurfsTurfIdRouteImport } from './routes/campaigns/$campaignId/canvassing/turfs/$turfId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsNewRoute = CampaignsNewRouteImport.update({
  id: '/campaigns/new',
  path: '/campaigns/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsCampaignIdRoute = CampaignsCampaignIdRouteImport.update({
  id: '/campaigns/$campaignId',
  path: '/campaigns/$campaignId',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsCampaignIdVolunteersRoute =
  CampaignsCampaignIdVolunteersRouteImport.update({
    id: '/volunteers',
    path: '/volunteers',
    getParentRoute: () => CampaignsCampaignIdRoute,
  } as any)
const CampaignsCampaignIdSurveysRoute =
  CampaignsCampaignIdSurveysRouteImport.update({
    id: '/surveys',
    path: '/surveys',
    getParentRoute: () => CampaignsCampaignIdRoute,
  } as any)
const CampaignsCampaignIdPhoneBankingRoute =
  CampaignsCampaignIdPhoneBankingRouteImport.update({
    id: '/phone-banking',
    path: '/phone-banking',
    getParentRoute: () => CampaignsCampaignIdRoute,
  } as any)
const CampaignsCampaignIdDashboardRoute =
  CampaignsCampaignIdDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => CampaignsCampaignIdRoute,
  } as any)
const CampaignsCampaignIdCanvassingRoute =
  CampaignsCampaignIdCanvassingRouteImport.update({
    id: '/canvassing',
    path: '/canvassing',
    getParentRoute: () => CampaignsCampaignIdRoute,
  } as any)
const CampaignsCampaignIdVotersIndexRoute =
  CampaignsCampaignIdVotersIndexRouteImport.update({
    id: '/voters/',
    path: '/voters/',
    getParentRoute: () => CampaignsCampaignIdRoute,
  } as any)
const CampaignsCampaignIdSurveysIndexRoute =
  CampaignsCampaignIdSurveysIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CampaignsCampaignIdSurveysRoute,
  } as any)
const CampaignsCampaignIdCanvassingIndexRoute =
  CampaignsCampaignIdCanvassingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CampaignsCampaignIdCanvassingRoute,
  } as any)
const CampaignsCampaignIdVotersVoterIdRoute =
  CampaignsCampaignIdVotersVoterIdRouteImport.update({
    id: '/voters/$voterId',
    path: '/voters/$voterId',
    getParentRoute: () => CampaignsCampaignIdRoute,
  } as any)
const CampaignsCampaignIdCanvassingWalkListsWalkListIdRoute =
  CampaignsCampaignIdCanvassingWalkListsWalkListIdRouteImport.update({
    id: '/walk-lists/$walkListId',
    path: '/walk-lists/$walkListId',
    getParentRoute: () => CampaignsCampaignIdCanvassingRoute,
  } as any)
const CampaignsCampaignIdCanvassingTurfsNewRoute =
  CampaignsCampaignIdCanvassingTurfsNewRouteImport.update({
    id: '/turfs/new',
    path: '/turfs/new',
    getParentRoute: () => CampaignsCampaignIdCanvassingRoute,
  } as any)
const CampaignsCampaignIdCanvassingTurfsTurfIdRoute =
  CampaignsCampaignIdCanvassingTurfsTurfIdRouteImport.update({
    id: '/turfs/$turfId',
    path: '/turfs/$turfId',
    getParentRoute: () => CampaignsCampaignIdCanvassingRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRouteWithChildren
  '/campaigns/new': typeof CampaignsNewRoute
  '/campaigns/$campaignId/canvassing': typeof CampaignsCampaignIdCanvassingRouteWithChildren
  '/campaigns/$campaignId/dashboard': typeof CampaignsCampaignIdDashboardRoute
  '/campaigns/$campaignId/phone-banking': typeof CampaignsCampaignIdPhoneBankingRoute
  '/campaigns/$campaignId/surveys': typeof CampaignsCampaignIdSurveysRouteWithChildren
  '/campaigns/$campaignId/volunteers': typeof CampaignsCampaignIdVolunteersRoute
  '/campaigns/$campaignId/voters/$voterId': typeof CampaignsCampaignIdVotersVoterIdRoute
  '/campaigns/$campaignId/canvassing/': typeof CampaignsCampaignIdCanvassingIndexRoute
  '/campaigns/$campaignId/surveys/': typeof CampaignsCampaignIdSurveysIndexRoute
  '/campaigns/$campaignId/voters/': typeof CampaignsCampaignIdVotersIndexRoute
  '/campaigns/$campaignId/canvassing/turfs/$turfId': typeof CampaignsCampaignIdCanvassingTurfsTurfIdRoute
  '/campaigns/$campaignId/canvassing/turfs/new': typeof CampaignsCampaignIdCanvassingTurfsNewRoute
  '/campaigns/$campaignId/canvassing/walk-lists/$walkListId': typeof CampaignsCampaignIdCanvassingWalkListsWalkListIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRouteWithChildren
  '/campaigns/new': typeof CampaignsNewRoute
  '/campaigns/$campaignId/dashboard': typeof CampaignsCampaignIdDashboardRoute
  '/campaigns/$campaignId/phone-banking': typeof CampaignsCampaignIdPhoneBankingRoute
  '/campaigns/$campaignId/volunteers': typeof CampaignsCampaignIdVolunteersRoute
  '/campaigns/$campaignId/voters/$voterId': typeof CampaignsCampaignIdVotersVoterIdRoute
  '/campaigns/$campaignId/canvassing': typeof CampaignsCampaignIdCanvassingIndexRoute
  '/campaigns/$campaignId/surveys': typeof CampaignsCampaignIdSurveysIndexRoute
  '/campaigns/$campaignId/voters': typeof CampaignsCampaignIdVotersIndexRoute
  '/campaigns/$campaignId/canvassing/turfs/$turfId': typeof CampaignsCampaignIdCanvassingTurfsTurfIdRoute
  '/campaigns/$campaignId/canvassing/turfs/new': typeof CampaignsCampaignIdCanvassingTurfsNewRoute
  '/campaigns/$campaignId/canvassing/walk-lists/$walkListId': typeof CampaignsCampaignIdCanvassingWalkListsWalkListIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRouteWithChildren
  '/campaigns/new': typeof CampaignsNewRoute
  '/campaigns/$campaignId/canvassing': typeof CampaignsCampaignIdCanvassingRouteWithChildren
  '/campaigns/$campaignId/dashboard': typeof CampaignsCampaignIdDashboardRoute
  '/campaigns/$campaignId/phone-banking': typeof CampaignsCampaignIdPhoneBankingRoute
  '/campaigns/$campaignId/surveys': typeof CampaignsCampaignIdSurveysRouteWithChildren
  '/campaigns/$campaignId/volunteers': typeof CampaignsCampaignIdVolunteersRoute
  '/campaigns/$campaignId/voters/$voterId': typeof CampaignsCampaignIdVotersVoterIdRoute
  '/campaigns/$campaignId/canvassing/': typeof CampaignsCampaignIdCanvassingIndexRoute
  '/campaigns/$campaignId/surveys/': typeof CampaignsCampaignIdSurveysIndexRoute
  '/campaigns/$campaignId/voters/': typeof CampaignsCampaignIdVotersIndexRoute
  '/campaigns/$campaignId/canvassing/turfs/$turfId': typeof CampaignsCampaignIdCanvassingTurfsTurfIdRoute
  '/campaigns/$campaignId/canvassing/turfs/new': typeof CampaignsCampaignIdCanvassingTurfsNewRoute
  '/campaigns/$campaignId/canvassing/walk-lists/$walkListId': typeof CampaignsCampaignIdCanvassingWalkListsWalkListIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/login'
    | '/campaigns/$campaignId'
    | '/campaigns/new'
    | '/campaigns/$campaignId/canvassing'
    | '/campaigns/$campaignId/dashboard'
    | '/campaigns/$campaignId/phone-banking'
    | '/campaigns/$campaignId/surveys'
    | '/campaigns/$campaignId/volunteers'
    | '/campaigns/$campaignId/voters/$voterId'
    | '/campaigns/$campaignId/canvassing/'
    | '/campaigns/$campaignId/surveys/'
    | '/campaigns/$campaignId/voters/'
    | '/campaigns/$campaignId/canvassing/turfs/$turfId'
    | '/campaigns/$campaignId/canvassing/turfs/new'
    | '/campaigns/$campaignId/canvassing/walk-lists/$walkListId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callback'
    | '/login'
    | '/campaigns/$campaignId'
    | '/campaigns/new'
    | '/campaigns/$campaignId/dashboard'
    | '/campaigns/$campaignId/phone-banking'
    | '/campaigns/$campaignId/volunteers'
    | '/campaigns/$campaignId/voters/$voterId'
    | '/campaigns/$campaignId/canvassing'
    | '/campaigns/$campaignId/surveys'
    | '/campaigns/$campaignId/voters'
    | '/campaigns/$campaignId/canvassing/turfs/$turfId'
    | '/campaigns/$campaignId/canvassing/turfs/new'
    | '/campaigns/$campaignId/canvassing/walk-lists/$walkListId'
  id:
    | '__root__'
    | '/'
    | '/callback'
    | '/login'
    | '/campaigns/$campaignId'
    | '/campaigns/new'
    | '/campaigns/$campaignId/canvassing'
    | '/campaigns/$campaignId/dashboard'
    | '/campaigns/$campaignId/phone-banking'
    | '/campaigns/$campaignId/surveys'
    | '/campaigns/$campaignId/volunteers'
    | '/campaigns/$campaignId/voters/$voterId'
    | '/campaigns/$campaignId/canvassing/'
    | '/campaigns/$campaignId/surveys/'
    | '/campaigns/$campaignId/voters/'
    | '/campaigns/$campaignId/canvassing/turfs/$turfId'
    | '/campaigns/$campaignId/canvassing/turfs/new'
    | '/campaigns/$campaignId/canvassing/walk-lists/$walkListId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CallbackRoute: typeof CallbackRoute
  LoginRoute: typeof LoginRoute
  CampaignsCampaignIdRoute: typeof CampaignsCampaignIdRouteWithChildren
  CampaignsNewRoute: typeof CampaignsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/new': {
      id: '/campaigns/new'
      path: '/campaigns/new'
      fullPath: '/campaigns/new'
      preLoaderRoute: typeof CampaignsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignId': {
      id: '/campaigns/$campaignId'
      path: '/campaigns/$campaignId'
      fullPath: '/campaigns/$campaignId'
      preLoaderRoute: typeof CampaignsCampaignIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignId/volunteers': {
      id: '/campaigns/$campaignId/volunteers'
      path: '/volunteers'
      fullPath: '/campaigns/$campaignId/volunteers'
      preLoaderRoute: typeof CampaignsCampaignIdVolunteersRouteImport
      parentRoute: typeof CampaignsCampaignIdRoute
    }
    '/campaigns/$campaignId/surveys': {
      id: '/campaigns/$campaignId/surveys'
      path: '/surveys'
      fullPath: '/campaigns/$campaignId/surveys'
      preLoaderRoute: typeof CampaignsCampaignIdSurveysRouteImport
      parentRoute: typeof CampaignsCampaignIdRoute
    }
    '/campaigns/$campaignId/phone-banking': {
      id: '/campaigns/$campaignId/phone-banking'
      path: '/phone-banking'
      fullPath: '/campaigns/$campaignId/phone-banking'
      preLoaderRoute: typeof CampaignsCampaignIdPhoneBankingRouteImport
      parentRoute: typeof CampaignsCampaignIdRoute
    }
    '/campaigns/$campaignId/dashboard': {
      id: '/campaigns/$campaignId/dashboard'
      path: '/dashboard'
      fullPath: '/campaigns/$campaignId/dashboard'
      preLoaderRoute: typeof CampaignsCampaignIdDashboardRouteImport
      parentRoute: typeof CampaignsCampaignIdRoute
    }
    '/campaigns/$campaignId/canvassing': {
      id: '/campaigns/$campaignId/canvassing'
      path: '/canvassing'
      fullPath: '/campaigns/$campaignId/canvassing'
      preLoaderRoute: typeof CampaignsCampaignIdCanvassingRouteImport
      parentRoute: typeof CampaignsCampaignIdRoute
    }
    '/campaigns/$campaignId/voters/': {
      id: '/campaigns/$campaignId/voters/'
      path: '/voters'
      fullPath: '/campaigns/$campaignId/voters/'
      preLoaderRoute: typeof CampaignsCampaignIdVotersIndexRouteImport
      parentRoute: typeof CampaignsCampaignIdRoute
    }
    '/campaigns/$campaignId/surveys/': {
      id: '/campaigns/$campaignId/surveys/'
      path: '/'
      fullPath: '/campaigns/$campaignId/surveys/'
      preLoaderRoute: typeof CampaignsCampaignIdSurveysIndexRouteImport
      parentRoute: typeof CampaignsCampaignIdSurveysRoute
    }
    '/campaigns/$campaignId/canvassing/': {
      id: '/campaigns/$campaignId/canvassing/'
      path: '/'
      fullPath: '/campaigns/$campaignId/canvassing/'
      preLoaderRoute: typeof CampaignsCampaignIdCanvassingIndexRouteImport
      parentRoute: typeof CampaignsCampaignIdCanvassingRoute
    }
    '/campaigns/$campaignId/voters/$voterId': {
      id: '/campaigns/$campaignId/voters/$voterId'
      path: '/voters/$voterId'
      fullPath: '/campaigns/$campaignId/voters/$voterId'
      preLoaderRoute: typeof CampaignsCampaignIdVotersVoterIdRouteImport
      parentRoute: typeof CampaignsCampaignIdRoute
    }
    '/campaigns/$campaignId/canvassing/walk-lists/$walkListId': {
      id: '/campaigns/$campaignId/canvassing/walk-lists/$walkListId'
      path: '/walk-lists/$walkListId'
      fullPath: '/campaigns/$campaignId/canvassing/walk-lists/$walkListId'
      preLoaderRoute: typeof CampaignsCampaignIdCanvassingWalkListsWalkListIdRouteImport
      parentRoute: typeof CampaignsCampaignIdCanvassingRoute
    }
    '/campaigns/$campaignId/canvassing/turfs/new': {
      id: '/campaigns/$campaignId/canvassing/turfs/new'
      path: '/turfs/new'
      fullPath: '/campaigns/$campaignId/canvassing/turfs/new'
      preLoaderRoute: typeof CampaignsCampaignIdCanvassingTurfsNewRouteImport
      parentRoute: typeof CampaignsCampaignIdCanvassingRoute
    }
    '/campaigns/$campaignId/canvassing/turfs/$turfId': {
      id: '/campaigns/$campaignId/canvassing/turfs/$turfId'
      path: '/turfs/$turfId'
      fullPath: '/campaigns/$campaignId/canvassing/turfs/$turfId'
      preLoaderRoute: typeof CampaignsCampaignIdCanvassingTurfsTurfIdRouteImport
      parentRoute: typeof CampaignsCampaignIdCanvassingRoute
    }
  }
}

interface CampaignsCampaignIdCanvassingRouteChildren {
  CampaignsCampaignIdCanvassingIndexRoute: typeof CampaignsCampaignIdCanvassingIndexRoute
  CampaignsCampaignIdCanvassingTurfsTurfIdRoute: typeof CampaignsCampaignIdCanvassingTurfsTurfIdRoute
  CampaignsCampaignIdCanvassingTurfsNewRoute: typeof CampaignsCampaignIdCanvassingTurfsNewRoute
  CampaignsCampaignIdCanvassingWalkListsWalkListIdRoute: typeof CampaignsCampaignIdCanvassingWalkListsWalkListIdRoute
}

const CampaignsCampaignIdCanvassingRouteChildren: CampaignsCampaignIdCanvassingRouteChildren =
  {
    CampaignsCampaignIdCanvassingIndexRoute:
      CampaignsCampaignIdCanvassingIndexRoute,
    CampaignsCampaignIdCanvassingTurfsTurfIdRoute:
      CampaignsCampaignIdCanvassingTurfsTurfIdRoute,
    CampaignsCampaignIdCanvassingTurfsNewRoute:
      CampaignsCampaignIdCanvassingTurfsNewRoute,
    CampaignsCampaignIdCanvassingWalkListsWalkListIdRoute:
      CampaignsCampaignIdCanvassingWalkListsWalkListIdRoute,
  }

const CampaignsCampaignIdCanvassingRouteWithChildren =
  CampaignsCampaignIdCanvassingRoute._addFileChildren(
    CampaignsCampaignIdCanvassingRouteChildren,
  )

interface CampaignsCampaignIdSurveysRouteChildren {
  CampaignsCampaignIdSurveysIndexRoute: typeof CampaignsCampaignIdSurveysIndexRoute
}

const CampaignsCampaignIdSurveysRouteChildren: CampaignsCampaignIdSurveysRouteChildren =
  {
    CampaignsCampaignIdSurveysIndexRoute: CampaignsCampaignIdSurveysIndexRoute,
  }

const CampaignsCampaignIdSurveysRouteWithChildren =
  CampaignsCampaignIdSurveysRoute._addFileChildren(
    CampaignsCampaignIdSurveysRouteChildren,
  )

interface CampaignsCampaignIdRouteChildren {
  CampaignsCampaignIdCanvassingRoute: typeof CampaignsCampaignIdCanvassingRouteWithChildren
  CampaignsCampaignIdDashboardRoute: typeof CampaignsCampaignIdDashboardRoute
  CampaignsCampaignIdPhoneBankingRoute: typeof CampaignsCampaignIdPhoneBankingRoute
  CampaignsCampaignIdSurveysRoute: typeof CampaignsCampaignIdSurveysRouteWithChildren
  CampaignsCampaignIdVolunteersRoute: typeof CampaignsCampaignIdVolunteersRoute
  CampaignsCampaignIdVotersVoterIdRoute: typeof CampaignsCampaignIdVotersVoterIdRoute
  CampaignsCampaignIdVotersIndexRoute: typeof CampaignsCampaignIdVotersIndexRoute
}

const CampaignsCampaignIdRouteChildren: CampaignsCampaignIdRouteChildren = {
  CampaignsCampaignIdCanvassingRoute:
    CampaignsCampaignIdCanvassingRouteWithChildren,
  CampaignsCampaignIdDashboardRoute: CampaignsCampaignIdDashboardRoute,
  CampaignsCampaignIdPhoneBankingRoute: CampaignsCampaignIdPhoneBankingRoute,
  CampaignsCampaignIdSurveysRoute: CampaignsCampaignIdSurveysRouteWithChildren,
  CampaignsCampaignIdVolunteersRoute: CampaignsCampaignIdVolunteersRoute,
  CampaignsCampaignIdVotersVoterIdRoute: CampaignsCampaignIdVotersVoterIdRoute,
  CampaignsCampaignIdVotersIndexRoute: CampaignsCampaignIdVotersIndexRoute,
}

const CampaignsCampaignIdRouteWithChildren =
  CampaignsCampaignIdRoute._addFileChildren(CampaignsCampaignIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CallbackRoute: CallbackRoute,
  LoginRoute: LoginRoute,
  CampaignsCampaignIdRoute: CampaignsCampaignIdRouteWithChildren,
  CampaignsNewRoute: CampaignsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
