/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrgSettingsRouteImport } from './routes/org/settings'
import { Route as OrgMembersRouteImport } from './routes/org/members'
import { Route as FieldCampaignIdRouteImport } from './routes/field/$campaignId'
import { Route as CampaignsNewRouteImport } from './routes/campaigns/new'
import { Route as CampaignsCampaignIdRouteImport } from './routes/campaigns/$campaignId'
import { Route as FieldCampaignIdIndexRouteImport } from './routes/field/$campaignId/index'
import { Route as FieldCampaignIdPhoneBankingRouteImport } from './routes/field/$campaignId/phone-banking'
import { Route as FieldCampaignIdCanvassingRouteImport } from './routes/field/$campaignId/canvassing'
import { Route as CampaignsCampaignIdVotersRouteImport } from './routes/campaigns/$campaignId/voters'
import { Route as CampaignsCampaignIdVolunteersRouteImport } from './routes/campaigns/$campaignId/volunteers'
import { Route as CampaignsCampaignIdSurveysRouteImport } from './routes/campaigns/$campaignId/surveys'
import { Route as CampaignsCampaignIdSettingsRouteImport } from './routes/campaigns/$campaignId/settings'
import { Route as CampaignsCampaignIdPhoneBankingRouteImport } from './routes/campaigns/$campaignId/phone-banking'
import { Route as CampaignsCampaignIdDashboardRouteImport } from './routes/campaigns/$campaignId/dashboard'
import { Route as CampaignsCampaignIdCanvassingRouteImport } from './routes/campaigns/$campaignId/canvassing'
import { Route as CampaignsCampaignIdVotersIndexRouteImport } from './routes/campaigns/$campaignId/voters/index'
import { Route as CampaignsCampaignIdVolunteersIndexRouteImport } from './routes/campaigns/$campaignId/volunteers/index'
import { Route as CampaignsCampaignIdSurveysIndexRouteImport } from './routes/campaigns/$campaignId/surveys/index'
import { Route as CampaignsCampaignIdSettingsIndexRouteImport } from './routes/campaigns/$campaignId/settings/index'
import { Route as CampaignsCampaignIdPhoneBankingIndexRouteImport } from './routes/campaigns/$campaignId/phone-banking/index'
import { Route as CampaignsCampaignIdCanvassingIndexRouteImport } from './routes/campaigns/$campaignId/canvassing/index'
import { Route as CampaignsCampaignIdVotersVoterIdRouteImport } from './routes/campaigns/$campaignId/voters/$voterId'
import { Route as CampaignsCampaignIdSurveysScriptIdRouteImport } from './routes/campaigns/$campaignId/surveys/$scriptId'
import { Route as CampaignsCampaignIdSettingsMembersRouteImport } from './routes/campaigns/$campaignId/settings/members'
import { Route as CampaignsCampaignIdSettingsGeneralRouteImport } from './routes/campaigns/$campaignId/settings/general'
import { Route as CampaignsCampaignIdSettingsDangerRouteImport } from './routes/campaigns/$campaignId/settings/danger'
import { Route as CampaignsCampaignIdPhoneBankingMessagesRouteImport } from './routes/campaigns/$campaignId/phone-banking/messages'
import { Route as CampaignsCampaignIdVotersTagsIndexRouteImport } from './routes/campaigns/$campaignId/voters/tags/index'
import { Route as CampaignsCampaignIdVotersListsIndexRouteImport } from './routes/campaigns/$campaignId/voters/lists/index'
import { Route as CampaignsCampaignIdVotersImportsIndexRouteImport } from './routes/campaigns/$campaignId/voters/imports/index'
import { Route as CampaignsCampaignIdVolunteersTagsIndexRouteImport } from './routes/campaigns/$campaignId/volunteers/tags/index'
import { Route as CampaignsCampaignIdVolunteersShiftsIndexRouteImport } from './routes/campaigns/$campaignId/volunteers/shifts/index'
import { Route as CampaignsCampaignIdVolunteersRosterIndexRouteImport } from './routes/campaigns/$campaignId/volunteers/roster/index'
import { Route as CampaignsCampaignIdVolunteersRegisterIndexRouteImport } from './routes/campaigns/$campaignId/volunteers/register/index'
import { Route as CampaignsCampaignIdVolunteersVolunteerIdIndexRouteImport } from './routes/campaigns/$campaignId/volunteers/$volunteerId/index'
import { Route as CampaignsCampaignIdPhoneBankingSessionsIndexRouteImport } from './routes/campaigns/$campaignId/phone-banking/sessions/index'
import { Route as CampaignsCampaignIdPhoneBankingMySessionsIndexRouteImport } from './routes/campaigns/$campaignId/phone-banking/my-sessions/index'
import { Route as CampaignsCampaignIdPhoneBankingDncIndexRouteImport } from './routes/campaigns/$campaignId/phone-banking/dnc/index'
import { Route as CampaignsCampaignIdPhoneBankingCallListsIndexRouteImport } from './routes/campaigns/$campaignId/phone-banking/call-lists/index'
import { Route as CampaignsCampaignIdVotersListsListIdRouteImport } from './routes/campaigns/$campaignId/voters/lists/$listId'
import { Route as CampaignsCampaignIdVotersImportsNewRouteImport } from './routes/campaigns/$campaignId/voters/imports/new'
import { Route as CampaignsCampaignIdPhoneBankingCallListsCallListIdRouteImport } from './routes/campaigns/$campaignId/phone-banking/call-lists/$callListId'
import { Route as CampaignsCampaignIdCanvassingWalkListsWalkListIdRouteImport } from './routes/campaigns/$campaignId/canvassing/walk-lists/$walkListId'
import { Route as CampaignsCampaignIdCanvassingTurfsNewRouteImport } from './routes/campaigns/$campaignId/canvassing/turfs/new'
import { Route as CampaignsCampaignIdCanvassingTurfsTurfIdRouteImport } from './routes/campaigns/$campaignId/canvassing/turfs/$turfId'
import { Route as CampaignsCampaignIdVolunteersShiftsShiftIdIndexRouteImport } from './routes/campaigns/$campaignId/volunteers/shifts/$shiftId/index'
import { Route as CampaignsCampaignIdPhoneBankingSessionsSessionIdIndexRouteImport } from './routes/campaigns/$campaignId/phone-banking/sessions/$sessionId/index'
import { Route as CampaignsCampaignIdPhoneBankingSessionsSessionIdCallRouteImport } from './routes/campaigns/$campaignId/phone-banking/sessions/$sessionId/call'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSettingsRoute = OrgSettingsRouteImport.update({
  id: '/org/settings',
  path: '/org/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgMembersRoute = OrgMembersRouteImport.update({
  id: '/org/members',
  path: '/org/members',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldCampaignIdRoute = FieldCampaignIdRouteImport.update({
  id: '/field/$campaignId',
  path: '/field/$campaignId',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsNewRoute = CampaignsNewRouteImport.update({
  id: '/campaigns/new',
  path: '/campaigns/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsCampaignIdRoute = CampaignsCampaignIdRouteImport.update({
  id: '/campaigns/$campaignId',
  path: '/campaigns/$campaignId',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldCampaignIdIndexRoute = FieldCampaignIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FieldCampaignIdRoute,
} as any)
const FieldCampaignIdPhoneBankingRoute =
  FieldCampaignIdPhoneBankingRouteImport.update({
    id: '/phone-banking',
    path: '/phone-banking',
    getParentRoute: () => FieldCampaignIdRoute,
  } as any)
const FieldCampaignIdCanvassingRoute =
  FieldCampaignIdCanvassingRouteImport.update({
    id: '/canvassing',
    path: '/canvassing',
    getParentRoute: () => FieldCampaignIdRoute,
  } as any)
const CampaignsCampaignIdVotersRoute =
  CampaignsCampaignIdVotersRouteImport.update({
    id: '/voters',
    path: '/voters',
    getParentRoute: () => CampaignsCampaignIdRoute,
  } as any)
const CampaignsCampaignIdVolunteersRoute =
  CampaignsCampaignIdVolunteersRouteImport.update({
    id: '/volunteers',
    path: '/volunteers',
    getParentRoute: () => CampaignsCampaignIdRoute,
  } as any)
const CampaignsCampaignIdSurveysRoute =
  CampaignsCampaignIdSurveysRouteImport.update({
    id: '/surveys',
    path: '/surveys',
    getParentRoute: () => CampaignsCampaignIdRoute,
  } as any)
const CampaignsCampaignIdSettingsRoute =
  CampaignsCampaignIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => CampaignsCampaignIdRoute,
  } as any)
const CampaignsCampaignIdPhoneBankingRoute =
  CampaignsCampaignIdPhoneBankingRouteImport.update({
    id: '/phone-banking',
    path: '/phone-banking',
    getParentRoute: () => CampaignsCampaignIdRoute,
  } as any)
const CampaignsCampaignIdDashboardRoute =
  CampaignsCampaignIdDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => CampaignsCampaignIdRoute,
  } as any)
const CampaignsCampaignIdCanvassingRoute =
  CampaignsCampaignIdCanvassingRouteImport.update({
    id: '/canvassing',
    path: '/canvassing',
    getParentRoute: () => CampaignsCampaignIdRoute,
  } as any)
const CampaignsCampaignIdVotersIndexRoute =
  CampaignsCampaignIdVotersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CampaignsCampaignIdVotersRoute,
  } as any)
const CampaignsCampaignIdVolunteersIndexRoute =
  CampaignsCampaignIdVolunteersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CampaignsCampaignIdVolunteersRoute,
  } as any)
const CampaignsCampaignIdSurveysIndexRoute =
  CampaignsCampaignIdSurveysIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CampaignsCampaignIdSurveysRoute,
  } as any)
const CampaignsCampaignIdSettingsIndexRoute =
  CampaignsCampaignIdSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CampaignsCampaignIdSettingsRoute,
  } as any)
const CampaignsCampaignIdPhoneBankingIndexRoute =
  CampaignsCampaignIdPhoneBankingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CampaignsCampaignIdPhoneBankingRoute,
  } as any)
const CampaignsCampaignIdCanvassingIndexRoute =
  CampaignsCampaignIdCanvassingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CampaignsCampaignIdCanvassingRoute,
  } as any)
const CampaignsCampaignIdVotersVoterIdRoute =
  CampaignsCampaignIdVotersVoterIdRouteImport.update({
    id: '/$voterId',
    path: '/$voterId',
    getParentRoute: () => CampaignsCampaignIdVotersRoute,
  } as any)
const CampaignsCampaignIdSurveysScriptIdRoute =
  CampaignsCampaignIdSurveysScriptIdRouteImport.update({
    id: '/$scriptId',
    path: '/$scriptId',
    getParentRoute: () => CampaignsCampaignIdSurveysRoute,
  } as any)
const CampaignsCampaignIdSettingsMembersRoute =
  CampaignsCampaignIdSettingsMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => CampaignsCampaignIdSettingsRoute,
  } as any)
const CampaignsCampaignIdSettingsGeneralRoute =
  CampaignsCampaignIdSettingsGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => CampaignsCampaignIdSettingsRoute,
  } as any)
const CampaignsCampaignIdSettingsDangerRoute =
  CampaignsCampaignIdSettingsDangerRouteImport.update({
    id: '/danger',
    path: '/danger',
    getParentRoute: () => CampaignsCampaignIdSettingsRoute,
  } as any)
const CampaignsCampaignIdPhoneBankingMessagesRoute =
  CampaignsCampaignIdPhoneBankingMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => CampaignsCampaignIdPhoneBankingRoute,
  } as any)
const CampaignsCampaignIdVotersTagsIndexRoute =
  CampaignsCampaignIdVotersTagsIndexRouteImport.update({
    id: '/tags/',
    path: '/tags/',
    getParentRoute: () => CampaignsCampaignIdVotersRoute,
  } as any)
const CampaignsCampaignIdVotersListsIndexRoute =
  CampaignsCampaignIdVotersListsIndexRouteImport.update({
    id: '/lists/',
    path: '/lists/',
    getParentRoute: () => CampaignsCampaignIdVotersRoute,
  } as any)
const CampaignsCampaignIdVotersImportsIndexRoute =
  CampaignsCampaignIdVotersImportsIndexRouteImport.update({
    id: '/imports/',
    path: '/imports/',
    getParentRoute: () => CampaignsCampaignIdVotersRoute,
  } as any)
const CampaignsCampaignIdVolunteersTagsIndexRoute =
  CampaignsCampaignIdVolunteersTagsIndexRouteImport.update({
    id: '/tags/',
    path: '/tags/',
    getParentRoute: () => CampaignsCampaignIdVolunteersRoute,
  } as any)
const CampaignsCampaignIdVolunteersShiftsIndexRoute =
  CampaignsCampaignIdVolunteersShiftsIndexRouteImport.update({
    id: '/shifts/',
    path: '/shifts/',
    getParentRoute: () => CampaignsCampaignIdVolunteersRoute,
  } as any)
const CampaignsCampaignIdVolunteersRosterIndexRoute =
  CampaignsCampaignIdVolunteersRosterIndexRouteImport.update({
    id: '/roster/',
    path: '/roster/',
    getParentRoute: () => CampaignsCampaignIdVolunteersRoute,
  } as any)
const CampaignsCampaignIdVolunteersRegisterIndexRoute =
  CampaignsCampaignIdVolunteersRegisterIndexRouteImport.update({
    id: '/register/',
    path: '/register/',
    getParentRoute: () => CampaignsCampaignIdVolunteersRoute,
  } as any)
const CampaignsCampaignIdVolunteersVolunteerIdIndexRoute =
  CampaignsCampaignIdVolunteersVolunteerIdIndexRouteImport.update({
    id: '/$volunteerId/',
    path: '/$volunteerId/',
    getParentRoute: () => CampaignsCampaignIdVolunteersRoute,
  } as any)
const CampaignsCampaignIdPhoneBankingSessionsIndexRoute =
  CampaignsCampaignIdPhoneBankingSessionsIndexRouteImport.update({
    id: '/sessions/',
    path: '/sessions/',
    getParentRoute: () => CampaignsCampaignIdPhoneBankingRoute,
  } as any)
const CampaignsCampaignIdPhoneBankingMySessionsIndexRoute =
  CampaignsCampaignIdPhoneBankingMySessionsIndexRouteImport.update({
    id: '/my-sessions/',
    path: '/my-sessions/',
    getParentRoute: () => CampaignsCampaignIdPhoneBankingRoute,
  } as any)
const CampaignsCampaignIdPhoneBankingDncIndexRoute =
  CampaignsCampaignIdPhoneBankingDncIndexRouteImport.update({
    id: '/dnc/',
    path: '/dnc/',
    getParentRoute: () => CampaignsCampaignIdPhoneBankingRoute,
  } as any)
const CampaignsCampaignIdPhoneBankingCallListsIndexRoute =
  CampaignsCampaignIdPhoneBankingCallListsIndexRouteImport.update({
    id: '/call-lists/',
    path: '/call-lists/',
    getParentRoute: () => CampaignsCampaignIdPhoneBankingRoute,
  } as any)
const CampaignsCampaignIdVotersListsListIdRoute =
  CampaignsCampaignIdVotersListsListIdRouteImport.update({
    id: '/lists/$listId',
    path: '/lists/$listId',
    getParentRoute: () => CampaignsCampaignIdVotersRoute,
  } as any)
const CampaignsCampaignIdVotersImportsNewRoute =
  CampaignsCampaignIdVotersImportsNewRouteImport.update({
    id: '/imports/new',
    path: '/imports/new',
    getParentRoute: () => CampaignsCampaignIdVotersRoute,
  } as any)
const CampaignsCampaignIdPhoneBankingCallListsCallListIdRoute =
  CampaignsCampaignIdPhoneBankingCallListsCallListIdRouteImport.update({
    id: '/call-lists/$callListId',
    path: '/call-lists/$callListId',
    getParentRoute: () => CampaignsCampaignIdPhoneBankingRoute,
  } as any)
const CampaignsCampaignIdCanvassingWalkListsWalkListIdRoute =
  CampaignsCampaignIdCanvassingWalkListsWalkListIdRouteImport.update({
    id: '/walk-lists/$walkListId',
    path: '/walk-lists/$walkListId',
    getParentRoute: () => CampaignsCampaignIdCanvassingRoute,
  } as any)
const CampaignsCampaignIdCanvassingTurfsNewRoute =
  CampaignsCampaignIdCanvassingTurfsNewRouteImport.update({
    id: '/turfs/new',
    path: '/turfs/new',
    getParentRoute: () => CampaignsCampaignIdCanvassingRoute,
  } as any)
const CampaignsCampaignIdCanvassingTurfsTurfIdRoute =
  CampaignsCampaignIdCanvassingTurfsTurfIdRouteImport.update({
    id: '/turfs/$turfId',
    path: '/turfs/$turfId',
    getParentRoute: () => CampaignsCampaignIdCanvassingRoute,
  } as any)
const CampaignsCampaignIdVolunteersShiftsShiftIdIndexRoute =
  CampaignsCampaignIdVolunteersShiftsShiftIdIndexRouteImport.update({
    id: '/shifts/$shiftId/',
    path: '/shifts/$shiftId/',
    getParentRoute: () => CampaignsCampaignIdVolunteersRoute,
  } as any)
const CampaignsCampaignIdPhoneBankingSessionsSessionIdIndexRoute =
  CampaignsCampaignIdPhoneBankingSessionsSessionIdIndexRouteImport.update({
    id: '/sessions/$sessionId/',
    path: '/sessions/$sessionId/',
    getParentRoute: () => CampaignsCampaignIdPhoneBankingRoute,
  } as any)
const CampaignsCampaignIdPhoneBankingSessionsSessionIdCallRoute =
  CampaignsCampaignIdPhoneBankingSessionsSessionIdCallRouteImport.update({
    id: '/sessions/$sessionId/call',
    path: '/sessions/$sessionId/call',
    getParentRoute: () => CampaignsCampaignIdPhoneBankingRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRouteWithChildren
  '/campaigns/new': typeof CampaignsNewRoute
  '/field/$campaignId': typeof FieldCampaignIdRouteWithChildren
  '/org/members': typeof OrgMembersRoute
  '/org/settings': typeof OrgSettingsRoute
  '/campaigns/$campaignId/canvassing': typeof CampaignsCampaignIdCanvassingRouteWithChildren
  '/campaigns/$campaignId/dashboard': typeof CampaignsCampaignIdDashboardRoute
  '/campaigns/$campaignId/phone-banking': typeof CampaignsCampaignIdPhoneBankingRouteWithChildren
  '/campaigns/$campaignId/settings': typeof CampaignsCampaignIdSettingsRouteWithChildren
  '/campaigns/$campaignId/surveys': typeof CampaignsCampaignIdSurveysRouteWithChildren
  '/campaigns/$campaignId/volunteers': typeof CampaignsCampaignIdVolunteersRouteWithChildren
  '/campaigns/$campaignId/voters': typeof CampaignsCampaignIdVotersRouteWithChildren
  '/field/$campaignId/canvassing': typeof FieldCampaignIdCanvassingRoute
  '/field/$campaignId/phone-banking': typeof FieldCampaignIdPhoneBankingRoute
  '/field/$campaignId/': typeof FieldCampaignIdIndexRoute
  '/campaigns/$campaignId/phone-banking/messages': typeof CampaignsCampaignIdPhoneBankingMessagesRoute
  '/campaigns/$campaignId/settings/danger': typeof CampaignsCampaignIdSettingsDangerRoute
  '/campaigns/$campaignId/settings/general': typeof CampaignsCampaignIdSettingsGeneralRoute
  '/campaigns/$campaignId/settings/members': typeof CampaignsCampaignIdSettingsMembersRoute
  '/campaigns/$campaignId/surveys/$scriptId': typeof CampaignsCampaignIdSurveysScriptIdRoute
  '/campaigns/$campaignId/voters/$voterId': typeof CampaignsCampaignIdVotersVoterIdRoute
  '/campaigns/$campaignId/canvassing/': typeof CampaignsCampaignIdCanvassingIndexRoute
  '/campaigns/$campaignId/phone-banking/': typeof CampaignsCampaignIdPhoneBankingIndexRoute
  '/campaigns/$campaignId/settings/': typeof CampaignsCampaignIdSettingsIndexRoute
  '/campaigns/$campaignId/surveys/': typeof CampaignsCampaignIdSurveysIndexRoute
  '/campaigns/$campaignId/volunteers/': typeof CampaignsCampaignIdVolunteersIndexRoute
  '/campaigns/$campaignId/voters/': typeof CampaignsCampaignIdVotersIndexRoute
  '/campaigns/$campaignId/canvassing/turfs/$turfId': typeof CampaignsCampaignIdCanvassingTurfsTurfIdRoute
  '/campaigns/$campaignId/canvassing/turfs/new': typeof CampaignsCampaignIdCanvassingTurfsNewRoute
  '/campaigns/$campaignId/canvassing/walk-lists/$walkListId': typeof CampaignsCampaignIdCanvassingWalkListsWalkListIdRoute
  '/campaigns/$campaignId/phone-banking/call-lists/$callListId': typeof CampaignsCampaignIdPhoneBankingCallListsCallListIdRoute
  '/campaigns/$campaignId/voters/imports/new': typeof CampaignsCampaignIdVotersImportsNewRoute
  '/campaigns/$campaignId/voters/lists/$listId': typeof CampaignsCampaignIdVotersListsListIdRoute
  '/campaigns/$campaignId/phone-banking/call-lists/': typeof CampaignsCampaignIdPhoneBankingCallListsIndexRoute
  '/campaigns/$campaignId/phone-banking/dnc/': typeof CampaignsCampaignIdPhoneBankingDncIndexRoute
  '/campaigns/$campaignId/phone-banking/my-sessions/': typeof CampaignsCampaignIdPhoneBankingMySessionsIndexRoute
  '/campaigns/$campaignId/phone-banking/sessions/': typeof CampaignsCampaignIdPhoneBankingSessionsIndexRoute
  '/campaigns/$campaignId/volunteers/$volunteerId/': typeof CampaignsCampaignIdVolunteersVolunteerIdIndexRoute
  '/campaigns/$campaignId/volunteers/register/': typeof CampaignsCampaignIdVolunteersRegisterIndexRoute
  '/campaigns/$campaignId/volunteers/roster/': typeof CampaignsCampaignIdVolunteersRosterIndexRoute
  '/campaigns/$campaignId/volunteers/shifts/': typeof CampaignsCampaignIdVolunteersShiftsIndexRoute
  '/campaigns/$campaignId/volunteers/tags/': typeof CampaignsCampaignIdVolunteersTagsIndexRoute
  '/campaigns/$campaignId/voters/imports/': typeof CampaignsCampaignIdVotersImportsIndexRoute
  '/campaigns/$campaignId/voters/lists/': typeof CampaignsCampaignIdVotersListsIndexRoute
  '/campaigns/$campaignId/voters/tags/': typeof CampaignsCampaignIdVotersTagsIndexRoute
  '/campaigns/$campaignId/phone-banking/sessions/$sessionId/call': typeof CampaignsCampaignIdPhoneBankingSessionsSessionIdCallRoute
  '/campaigns/$campaignId/phone-banking/sessions/$sessionId/': typeof CampaignsCampaignIdPhoneBankingSessionsSessionIdIndexRoute
  '/campaigns/$campaignId/volunteers/shifts/$shiftId/': typeof CampaignsCampaignIdVolunteersShiftsShiftIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRouteWithChildren
  '/campaigns/new': typeof CampaignsNewRoute
  '/org/members': typeof OrgMembersRoute
  '/org/settings': typeof OrgSettingsRoute
  '/campaigns/$campaignId/dashboard': typeof CampaignsCampaignIdDashboardRoute
  '/field/$campaignId/canvassing': typeof FieldCampaignIdCanvassingRoute
  '/field/$campaignId/phone-banking': typeof FieldCampaignIdPhoneBankingRoute
  '/field/$campaignId': typeof FieldCampaignIdIndexRoute
  '/campaigns/$campaignId/phone-banking/messages': typeof CampaignsCampaignIdPhoneBankingMessagesRoute
  '/campaigns/$campaignId/settings/danger': typeof CampaignsCampaignIdSettingsDangerRoute
  '/campaigns/$campaignId/settings/general': typeof CampaignsCampaignIdSettingsGeneralRoute
  '/campaigns/$campaignId/settings/members': typeof CampaignsCampaignIdSettingsMembersRoute
  '/campaigns/$campaignId/surveys/$scriptId': typeof CampaignsCampaignIdSurveysScriptIdRoute
  '/campaigns/$campaignId/voters/$voterId': typeof CampaignsCampaignIdVotersVoterIdRoute
  '/campaigns/$campaignId/canvassing': typeof CampaignsCampaignIdCanvassingIndexRoute
  '/campaigns/$campaignId/phone-banking': typeof CampaignsCampaignIdPhoneBankingIndexRoute
  '/campaigns/$campaignId/settings': typeof CampaignsCampaignIdSettingsIndexRoute
  '/campaigns/$campaignId/surveys': typeof CampaignsCampaignIdSurveysIndexRoute
  '/campaigns/$campaignId/volunteers': typeof CampaignsCampaignIdVolunteersIndexRoute
  '/campaigns/$campaignId/voters': typeof CampaignsCampaignIdVotersIndexRoute
  '/campaigns/$campaignId/canvassing/turfs/$turfId': typeof CampaignsCampaignIdCanvassingTurfsTurfIdRoute
  '/campaigns/$campaignId/canvassing/turfs/new': typeof CampaignsCampaignIdCanvassingTurfsNewRoute
  '/campaigns/$campaignId/canvassing/walk-lists/$walkListId': typeof CampaignsCampaignIdCanvassingWalkListsWalkListIdRoute
  '/campaigns/$campaignId/phone-banking/call-lists/$callListId': typeof CampaignsCampaignIdPhoneBankingCallListsCallListIdRoute
  '/campaigns/$campaignId/voters/imports/new': typeof CampaignsCampaignIdVotersImportsNewRoute
  '/campaigns/$campaignId/voters/lists/$listId': typeof CampaignsCampaignIdVotersListsListIdRoute
  '/campaigns/$campaignId/phone-banking/call-lists': typeof CampaignsCampaignIdPhoneBankingCallListsIndexRoute
  '/campaigns/$campaignId/phone-banking/dnc': typeof CampaignsCampaignIdPhoneBankingDncIndexRoute
  '/campaigns/$campaignId/phone-banking/my-sessions': typeof CampaignsCampaignIdPhoneBankingMySessionsIndexRoute
  '/campaigns/$campaignId/phone-banking/sessions': typeof CampaignsCampaignIdPhoneBankingSessionsIndexRoute
  '/campaigns/$campaignId/volunteers/$volunteerId': typeof CampaignsCampaignIdVolunteersVolunteerIdIndexRoute
  '/campaigns/$campaignId/volunteers/register': typeof CampaignsCampaignIdVolunteersRegisterIndexRoute
  '/campaigns/$campaignId/volunteers/roster': typeof CampaignsCampaignIdVolunteersRosterIndexRoute
  '/campaigns/$campaignId/volunteers/shifts': typeof CampaignsCampaignIdVolunteersShiftsIndexRoute
  '/campaigns/$campaignId/volunteers/tags': typeof CampaignsCampaignIdVolunteersTagsIndexRoute
  '/campaigns/$campaignId/voters/imports': typeof CampaignsCampaignIdVotersImportsIndexRoute
  '/campaigns/$campaignId/voters/lists': typeof CampaignsCampaignIdVotersListsIndexRoute
  '/campaigns/$campaignId/voters/tags': typeof CampaignsCampaignIdVotersTagsIndexRoute
  '/campaigns/$campaignId/phone-banking/sessions/$sessionId/call': typeof CampaignsCampaignIdPhoneBankingSessionsSessionIdCallRoute
  '/campaigns/$campaignId/phone-banking/sessions/$sessionId': typeof CampaignsCampaignIdPhoneBankingSessionsSessionIdIndexRoute
  '/campaigns/$campaignId/volunteers/shifts/$shiftId': typeof CampaignsCampaignIdVolunteersShiftsShiftIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRouteWithChildren
  '/campaigns/new': typeof CampaignsNewRoute
  '/field/$campaignId': typeof FieldCampaignIdRouteWithChildren
  '/org/members': typeof OrgMembersRoute
  '/org/settings': typeof OrgSettingsRoute
  '/campaigns/$campaignId/canvassing': typeof CampaignsCampaignIdCanvassingRouteWithChildren
  '/campaigns/$campaignId/dashboard': typeof CampaignsCampaignIdDashboardRoute
  '/campaigns/$campaignId/phone-banking': typeof CampaignsCampaignIdPhoneBankingRouteWithChildren
  '/campaigns/$campaignId/settings': typeof CampaignsCampaignIdSettingsRouteWithChildren
  '/campaigns/$campaignId/surveys': typeof CampaignsCampaignIdSurveysRouteWithChildren
  '/campaigns/$campaignId/volunteers': typeof CampaignsCampaignIdVolunteersRouteWithChildren
  '/campaigns/$campaignId/voters': typeof CampaignsCampaignIdVotersRouteWithChildren
  '/field/$campaignId/canvassing': typeof FieldCampaignIdCanvassingRoute
  '/field/$campaignId/phone-banking': typeof FieldCampaignIdPhoneBankingRoute
  '/field/$campaignId/': typeof FieldCampaignIdIndexRoute
  '/campaigns/$campaignId/phone-banking/messages': typeof CampaignsCampaignIdPhoneBankingMessagesRoute
  '/campaigns/$campaignId/settings/danger': typeof CampaignsCampaignIdSettingsDangerRoute
  '/campaigns/$campaignId/settings/general': typeof CampaignsCampaignIdSettingsGeneralRoute
  '/campaigns/$campaignId/settings/members': typeof CampaignsCampaignIdSettingsMembersRoute
  '/campaigns/$campaignId/surveys/$scriptId': typeof CampaignsCampaignIdSurveysScriptIdRoute
  '/campaigns/$campaignId/voters/$voterId': typeof CampaignsCampaignIdVotersVoterIdRoute
  '/campaigns/$campaignId/canvassing/': typeof CampaignsCampaignIdCanvassingIndexRoute
  '/campaigns/$campaignId/phone-banking/': typeof CampaignsCampaignIdPhoneBankingIndexRoute
  '/campaigns/$campaignId/settings/': typeof CampaignsCampaignIdSettingsIndexRoute
  '/campaigns/$campaignId/surveys/': typeof CampaignsCampaignIdSurveysIndexRoute
  '/campaigns/$campaignId/volunteers/': typeof CampaignsCampaignIdVolunteersIndexRoute
  '/campaigns/$campaignId/voters/': typeof CampaignsCampaignIdVotersIndexRoute
  '/campaigns/$campaignId/canvassing/turfs/$turfId': typeof CampaignsCampaignIdCanvassingTurfsTurfIdRoute
  '/campaigns/$campaignId/canvassing/turfs/new': typeof CampaignsCampaignIdCanvassingTurfsNewRoute
  '/campaigns/$campaignId/canvassing/walk-lists/$walkListId': typeof CampaignsCampaignIdCanvassingWalkListsWalkListIdRoute
  '/campaigns/$campaignId/phone-banking/call-lists/$callListId': typeof CampaignsCampaignIdPhoneBankingCallListsCallListIdRoute
  '/campaigns/$campaignId/voters/imports/new': typeof CampaignsCampaignIdVotersImportsNewRoute
  '/campaigns/$campaignId/voters/lists/$listId': typeof CampaignsCampaignIdVotersListsListIdRoute
  '/campaigns/$campaignId/phone-banking/call-lists/': typeof CampaignsCampaignIdPhoneBankingCallListsIndexRoute
  '/campaigns/$campaignId/phone-banking/dnc/': typeof CampaignsCampaignIdPhoneBankingDncIndexRoute
  '/campaigns/$campaignId/phone-banking/my-sessions/': typeof CampaignsCampaignIdPhoneBankingMySessionsIndexRoute
  '/campaigns/$campaignId/phone-banking/sessions/': typeof CampaignsCampaignIdPhoneBankingSessionsIndexRoute
  '/campaigns/$campaignId/volunteers/$volunteerId/': typeof CampaignsCampaignIdVolunteersVolunteerIdIndexRoute
  '/campaigns/$campaignId/volunteers/register/': typeof CampaignsCampaignIdVolunteersRegisterIndexRoute
  '/campaigns/$campaignId/volunteers/roster/': typeof CampaignsCampaignIdVolunteersRosterIndexRoute
  '/campaigns/$campaignId/volunteers/shifts/': typeof CampaignsCampaignIdVolunteersShiftsIndexRoute
  '/campaigns/$campaignId/volunteers/tags/': typeof CampaignsCampaignIdVolunteersTagsIndexRoute
  '/campaigns/$campaignId/voters/imports/': typeof CampaignsCampaignIdVotersImportsIndexRoute
  '/campaigns/$campaignId/voters/lists/': typeof CampaignsCampaignIdVotersListsIndexRoute
  '/campaigns/$campaignId/voters/tags/': typeof CampaignsCampaignIdVotersTagsIndexRoute
  '/campaigns/$campaignId/phone-banking/sessions/$sessionId/call': typeof CampaignsCampaignIdPhoneBankingSessionsSessionIdCallRoute
  '/campaigns/$campaignId/phone-banking/sessions/$sessionId/': typeof CampaignsCampaignIdPhoneBankingSessionsSessionIdIndexRoute
  '/campaigns/$campaignId/volunteers/shifts/$shiftId/': typeof CampaignsCampaignIdVolunteersShiftsShiftIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/login'
    | '/campaigns/$campaignId'
    | '/campaigns/new'
    | '/field/$campaignId'
    | '/org/members'
    | '/org/settings'
    | '/campaigns/$campaignId/canvassing'
    | '/campaigns/$campaignId/dashboard'
    | '/campaigns/$campaignId/phone-banking'
    | '/campaigns/$campaignId/settings'
    | '/campaigns/$campaignId/surveys'
    | '/campaigns/$campaignId/volunteers'
    | '/campaigns/$campaignId/voters'
    | '/field/$campaignId/canvassing'
    | '/field/$campaignId/phone-banking'
    | '/field/$campaignId/'
    | '/campaigns/$campaignId/phone-banking/messages'
    | '/campaigns/$campaignId/settings/danger'
    | '/campaigns/$campaignId/settings/general'
    | '/campaigns/$campaignId/settings/members'
    | '/campaigns/$campaignId/surveys/$scriptId'
    | '/campaigns/$campaignId/voters/$voterId'
    | '/campaigns/$campaignId/canvassing/'
    | '/campaigns/$campaignId/phone-banking/'
    | '/campaigns/$campaignId/settings/'
    | '/campaigns/$campaignId/surveys/'
    | '/campaigns/$campaignId/volunteers/'
    | '/campaigns/$campaignId/voters/'
    | '/campaigns/$campaignId/canvassing/turfs/$turfId'
    | '/campaigns/$campaignId/canvassing/turfs/new'
    | '/campaigns/$campaignId/canvassing/walk-lists/$walkListId'
    | '/campaigns/$campaignId/phone-banking/call-lists/$callListId'
    | '/campaigns/$campaignId/voters/imports/new'
    | '/campaigns/$campaignId/voters/lists/$listId'
    | '/campaigns/$campaignId/phone-banking/call-lists/'
    | '/campaigns/$campaignId/phone-banking/dnc/'
    | '/campaigns/$campaignId/phone-banking/my-sessions/'
    | '/campaigns/$campaignId/phone-banking/sessions/'
    | '/campaigns/$campaignId/volunteers/$volunteerId/'
    | '/campaigns/$campaignId/volunteers/register/'
    | '/campaigns/$campaignId/volunteers/roster/'
    | '/campaigns/$campaignId/volunteers/shifts/'
    | '/campaigns/$campaignId/volunteers/tags/'
    | '/campaigns/$campaignId/voters/imports/'
    | '/campaigns/$campaignId/voters/lists/'
    | '/campaigns/$campaignId/voters/tags/'
    | '/campaigns/$campaignId/phone-banking/sessions/$sessionId/call'
    | '/campaigns/$campaignId/phone-banking/sessions/$sessionId/'
    | '/campaigns/$campaignId/volunteers/shifts/$shiftId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callback'
    | '/login'
    | '/campaigns/$campaignId'
    | '/campaigns/new'
    | '/org/members'
    | '/org/settings'
    | '/campaigns/$campaignId/dashboard'
    | '/field/$campaignId/canvassing'
    | '/field/$campaignId/phone-banking'
    | '/field/$campaignId'
    | '/campaigns/$campaignId/phone-banking/messages'
    | '/campaigns/$campaignId/settings/danger'
    | '/campaigns/$campaignId/settings/general'
    | '/campaigns/$campaignId/settings/members'
    | '/campaigns/$campaignId/surveys/$scriptId'
    | '/campaigns/$campaignId/voters/$voterId'
    | '/campaigns/$campaignId/canvassing'
    | '/campaigns/$campaignId/phone-banking'
    | '/campaigns/$campaignId/settings'
    | '/campaigns/$campaignId/surveys'
    | '/campaigns/$campaignId/volunteers'
    | '/campaigns/$campaignId/voters'
    | '/campaigns/$campaignId/canvassing/turfs/$turfId'
    | '/campaigns/$campaignId/canvassing/turfs/new'
    | '/campaigns/$campaignId/canvassing/walk-lists/$walkListId'
    | '/campaigns/$campaignId/phone-banking/call-lists/$callListId'
    | '/campaigns/$campaignId/voters/imports/new'
    | '/campaigns/$campaignId/voters/lists/$listId'
    | '/campaigns/$campaignId/phone-banking/call-lists'
    | '/campaigns/$campaignId/phone-banking/dnc'
    | '/campaigns/$campaignId/phone-banking/my-sessions'
    | '/campaigns/$campaignId/phone-banking/sessions'
    | '/campaigns/$campaignId/volunteers/$volunteerId'
    | '/campaigns/$campaignId/volunteers/register'
    | '/campaigns/$campaignId/volunteers/roster'
    | '/campaigns/$campaignId/volunteers/shifts'
    | '/campaigns/$campaignId/volunteers/tags'
    | '/campaigns/$campaignId/voters/imports'
    | '/campaigns/$campaignId/voters/lists'
    | '/campaigns/$campaignId/voters/tags'
    | '/campaigns/$campaignId/phone-banking/sessions/$sessionId/call'
    | '/campaigns/$campaignId/phone-banking/sessions/$sessionId'
    | '/campaigns/$campaignId/volunteers/shifts/$shiftId'
  id:
    | '__root__'
    | '/'
    | '/callback'
    | '/login'
    | '/campaigns/$campaignId'
    | '/campaigns/new'
    | '/field/$campaignId'
    | '/org/members'
    | '/org/settings'
    | '/campaigns/$campaignId/canvassing'
    | '/campaigns/$campaignId/dashboard'
    | '/campaigns/$campaignId/phone-banking'
    | '/campaigns/$campaignId/settings'
    | '/campaigns/$campaignId/surveys'
    | '/campaigns/$campaignId/volunteers'
    | '/campaigns/$campaignId/voters'
    | '/field/$campaignId/canvassing'
    | '/field/$campaignId/phone-banking'
    | '/field/$campaignId/'
    | '/campaigns/$campaignId/phone-banking/messages'
    | '/campaigns/$campaignId/settings/danger'
    | '/campaigns/$campaignId/settings/general'
    | '/campaigns/$campaignId/settings/members'
    | '/campaigns/$campaignId/surveys/$scriptId'
    | '/campaigns/$campaignId/voters/$voterId'
    | '/campaigns/$campaignId/canvassing/'
    | '/campaigns/$campaignId/phone-banking/'
    | '/campaigns/$campaignId/settings/'
    | '/campaigns/$campaignId/surveys/'
    | '/campaigns/$campaignId/volunteers/'
    | '/campaigns/$campaignId/voters/'
    | '/campaigns/$campaignId/canvassing/turfs/$turfId'
    | '/campaigns/$campaignId/canvassing/turfs/new'
    | '/campaigns/$campaignId/canvassing/walk-lists/$walkListId'
    | '/campaigns/$campaignId/phone-banking/call-lists/$callListId'
    | '/campaigns/$campaignId/voters/imports/new'
    | '/campaigns/$campaignId/voters/lists/$listId'
    | '/campaigns/$campaignId/phone-banking/call-lists/'
    | '/campaigns/$campaignId/phone-banking/dnc/'
    | '/campaigns/$campaignId/phone-banking/my-sessions/'
    | '/campaigns/$campaignId/phone-banking/sessions/'
    | '/campaigns/$campaignId/volunteers/$volunteerId/'
    | '/campaigns/$campaignId/volunteers/register/'
    | '/campaigns/$campaignId/volunteers/roster/'
    | '/campaigns/$campaignId/volunteers/shifts/'
    | '/campaigns/$campaignId/volunteers/tags/'
    | '/campaigns/$campaignId/voters/imports/'
    | '/campaigns/$campaignId/voters/lists/'
    | '/campaigns/$campaignId/voters/tags/'
    | '/campaigns/$campaignId/phone-banking/sessions/$sessionId/call'
    | '/campaigns/$campaignId/phone-banking/sessions/$sessionId/'
    | '/campaigns/$campaignId/volunteers/shifts/$shiftId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CallbackRoute: typeof CallbackRoute
  LoginRoute: typeof LoginRoute
  CampaignsCampaignIdRoute: typeof CampaignsCampaignIdRouteWithChildren
  CampaignsNewRoute: typeof CampaignsNewRoute
  FieldCampaignIdRoute: typeof FieldCampaignIdRouteWithChildren
  OrgMembersRoute: typeof OrgMembersRoute
  OrgSettingsRoute: typeof OrgSettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/settings': {
      id: '/org/settings'
      path: '/org/settings'
      fullPath: '/org/settings'
      preLoaderRoute: typeof OrgSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/members': {
      id: '/org/members'
      path: '/org/members'
      fullPath: '/org/members'
      preLoaderRoute: typeof OrgMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field/$campaignId': {
      id: '/field/$campaignId'
      path: '/field/$campaignId'
      fullPath: '/field/$campaignId'
      preLoaderRoute: typeof FieldCampaignIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/new': {
      id: '/campaigns/new'
      path: '/campaigns/new'
      fullPath: '/campaigns/new'
      preLoaderRoute: typeof CampaignsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignId': {
      id: '/campaigns/$campaignId'
      path: '/campaigns/$campaignId'
      fullPath: '/campaigns/$campaignId'
      preLoaderRoute: typeof CampaignsCampaignIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field/$campaignId/': {
      id: '/field/$campaignId/'
      path: '/'
      fullPath: '/field/$campaignId/'
      preLoaderRoute: typeof FieldCampaignIdIndexRouteImport
      parentRoute: typeof FieldCampaignIdRoute
    }
    '/field/$campaignId/phone-banking': {
      id: '/field/$campaignId/phone-banking'
      path: '/phone-banking'
      fullPath: '/field/$campaignId/phone-banking'
      preLoaderRoute: typeof FieldCampaignIdPhoneBankingRouteImport
      parentRoute: typeof FieldCampaignIdRoute
    }
    '/field/$campaignId/canvassing': {
      id: '/field/$campaignId/canvassing'
      path: '/canvassing'
      fullPath: '/field/$campaignId/canvassing'
      preLoaderRoute: typeof FieldCampaignIdCanvassingRouteImport
      parentRoute: typeof FieldCampaignIdRoute
    }
    '/campaigns/$campaignId/voters': {
      id: '/campaigns/$campaignId/voters'
      path: '/voters'
      fullPath: '/campaigns/$campaignId/voters'
      preLoaderRoute: typeof CampaignsCampaignIdVotersRouteImport
      parentRoute: typeof CampaignsCampaignIdRoute
    }
    '/campaigns/$campaignId/volunteers': {
      id: '/campaigns/$campaignId/volunteers'
      path: '/volunteers'
      fullPath: '/campaigns/$campaignId/volunteers'
      preLoaderRoute: typeof CampaignsCampaignIdVolunteersRouteImport
      parentRoute: typeof CampaignsCampaignIdRoute
    }
    '/campaigns/$campaignId/surveys': {
      id: '/campaigns/$campaignId/surveys'
      path: '/surveys'
      fullPath: '/campaigns/$campaignId/surveys'
      preLoaderRoute: typeof CampaignsCampaignIdSurveysRouteImport
      parentRoute: typeof CampaignsCampaignIdRoute
    }
    '/campaigns/$campaignId/settings': {
      id: '/campaigns/$campaignId/settings'
      path: '/settings'
      fullPath: '/campaigns/$campaignId/settings'
      preLoaderRoute: typeof CampaignsCampaignIdSettingsRouteImport
      parentRoute: typeof CampaignsCampaignIdRoute
    }
    '/campaigns/$campaignId/phone-banking': {
      id: '/campaigns/$campaignId/phone-banking'
      path: '/phone-banking'
      fullPath: '/campaigns/$campaignId/phone-banking'
      preLoaderRoute: typeof CampaignsCampaignIdPhoneBankingRouteImport
      parentRoute: typeof CampaignsCampaignIdRoute
    }
    '/campaigns/$campaignId/dashboard': {
      id: '/campaigns/$campaignId/dashboard'
      path: '/dashboard'
      fullPath: '/campaigns/$campaignId/dashboard'
      preLoaderRoute: typeof CampaignsCampaignIdDashboardRouteImport
      parentRoute: typeof CampaignsCampaignIdRoute
    }
    '/campaigns/$campaignId/canvassing': {
      id: '/campaigns/$campaignId/canvassing'
      path: '/canvassing'
      fullPath: '/campaigns/$campaignId/canvassing'
      preLoaderRoute: typeof CampaignsCampaignIdCanvassingRouteImport
      parentRoute: typeof CampaignsCampaignIdRoute
    }
    '/campaigns/$campaignId/voters/': {
      id: '/campaigns/$campaignId/voters/'
      path: '/'
      fullPath: '/campaigns/$campaignId/voters/'
      preLoaderRoute: typeof CampaignsCampaignIdVotersIndexRouteImport
      parentRoute: typeof CampaignsCampaignIdVotersRoute
    }
    '/campaigns/$campaignId/volunteers/': {
      id: '/campaigns/$campaignId/volunteers/'
      path: '/'
      fullPath: '/campaigns/$campaignId/volunteers/'
      preLoaderRoute: typeof CampaignsCampaignIdVolunteersIndexRouteImport
      parentRoute: typeof CampaignsCampaignIdVolunteersRoute
    }
    '/campaigns/$campaignId/surveys/': {
      id: '/campaigns/$campaignId/surveys/'
      path: '/'
      fullPath: '/campaigns/$campaignId/surveys/'
      preLoaderRoute: typeof CampaignsCampaignIdSurveysIndexRouteImport
      parentRoute: typeof CampaignsCampaignIdSurveysRoute
    }
    '/campaigns/$campaignId/settings/': {
      id: '/campaigns/$campaignId/settings/'
      path: '/'
      fullPath: '/campaigns/$campaignId/settings/'
      preLoaderRoute: typeof CampaignsCampaignIdSettingsIndexRouteImport
      parentRoute: typeof CampaignsCampaignIdSettingsRoute
    }
    '/campaigns/$campaignId/phone-banking/': {
      id: '/campaigns/$campaignId/phone-banking/'
      path: '/'
      fullPath: '/campaigns/$campaignId/phone-banking/'
      preLoaderRoute: typeof CampaignsCampaignIdPhoneBankingIndexRouteImport
      parentRoute: typeof CampaignsCampaignIdPhoneBankingRoute
    }
    '/campaigns/$campaignId/canvassing/': {
      id: '/campaigns/$campaignId/canvassing/'
      path: '/'
      fullPath: '/campaigns/$campaignId/canvassing/'
      preLoaderRoute: typeof CampaignsCampaignIdCanvassingIndexRouteImport
      parentRoute: typeof CampaignsCampaignIdCanvassingRoute
    }
    '/campaigns/$campaignId/voters/$voterId': {
      id: '/campaigns/$campaignId/voters/$voterId'
      path: '/$voterId'
      fullPath: '/campaigns/$campaignId/voters/$voterId'
      preLoaderRoute: typeof CampaignsCampaignIdVotersVoterIdRouteImport
      parentRoute: typeof CampaignsCampaignIdVotersRoute
    }
    '/campaigns/$campaignId/surveys/$scriptId': {
      id: '/campaigns/$campaignId/surveys/$scriptId'
      path: '/$scriptId'
      fullPath: '/campaigns/$campaignId/surveys/$scriptId'
      preLoaderRoute: typeof CampaignsCampaignIdSurveysScriptIdRouteImport
      parentRoute: typeof CampaignsCampaignIdSurveysRoute
    }
    '/campaigns/$campaignId/settings/members': {
      id: '/campaigns/$campaignId/settings/members'
      path: '/members'
      fullPath: '/campaigns/$campaignId/settings/members'
      preLoaderRoute: typeof CampaignsCampaignIdSettingsMembersRouteImport
      parentRoute: typeof CampaignsCampaignIdSettingsRoute
    }
    '/campaigns/$campaignId/settings/general': {
      id: '/campaigns/$campaignId/settings/general'
      path: '/general'
      fullPath: '/campaigns/$campaignId/settings/general'
      preLoaderRoute: typeof CampaignsCampaignIdSettingsGeneralRouteImport
      parentRoute: typeof CampaignsCampaignIdSettingsRoute
    }
    '/campaigns/$campaignId/settings/danger': {
      id: '/campaigns/$campaignId/settings/danger'
      path: '/danger'
      fullPath: '/campaigns/$campaignId/settings/danger'
      preLoaderRoute: typeof CampaignsCampaignIdSettingsDangerRouteImport
      parentRoute: typeof CampaignsCampaignIdSettingsRoute
    }
    '/campaigns/$campaignId/phone-banking/messages': {
      id: '/campaigns/$campaignId/phone-banking/messages'
      path: '/messages'
      fullPath: '/campaigns/$campaignId/phone-banking/messages'
      preLoaderRoute: typeof CampaignsCampaignIdPhoneBankingMessagesRouteImport
      parentRoute: typeof CampaignsCampaignIdPhoneBankingRoute
    }
    '/campaigns/$campaignId/voters/tags/': {
      id: '/campaigns/$campaignId/voters/tags/'
      path: '/tags'
      fullPath: '/campaigns/$campaignId/voters/tags/'
      preLoaderRoute: typeof CampaignsCampaignIdVotersTagsIndexRouteImport
      parentRoute: typeof CampaignsCampaignIdVotersRoute
    }
    '/campaigns/$campaignId/voters/lists/': {
      id: '/campaigns/$campaignId/voters/lists/'
      path: '/lists'
      fullPath: '/campaigns/$campaignId/voters/lists/'
      preLoaderRoute: typeof CampaignsCampaignIdVotersListsIndexRouteImport
      parentRoute: typeof CampaignsCampaignIdVotersRoute
    }
    '/campaigns/$campaignId/voters/imports/': {
      id: '/campaigns/$campaignId/voters/imports/'
      path: '/imports'
      fullPath: '/campaigns/$campaignId/voters/imports/'
      preLoaderRoute: typeof CampaignsCampaignIdVotersImportsIndexRouteImport
      parentRoute: typeof CampaignsCampaignIdVotersRoute
    }
    '/campaigns/$campaignId/volunteers/tags/': {
      id: '/campaigns/$campaignId/volunteers/tags/'
      path: '/tags'
      fullPath: '/campaigns/$campaignId/volunteers/tags/'
      preLoaderRoute: typeof CampaignsCampaignIdVolunteersTagsIndexRouteImport
      parentRoute: typeof CampaignsCampaignIdVolunteersRoute
    }
    '/campaigns/$campaignId/volunteers/shifts/': {
      id: '/campaigns/$campaignId/volunteers/shifts/'
      path: '/shifts'
      fullPath: '/campaigns/$campaignId/volunteers/shifts/'
      preLoaderRoute: typeof CampaignsCampaignIdVolunteersShiftsIndexRouteImport
      parentRoute: typeof CampaignsCampaignIdVolunteersRoute
    }
    '/campaigns/$campaignId/volunteers/roster/': {
      id: '/campaigns/$campaignId/volunteers/roster/'
      path: '/roster'
      fullPath: '/campaigns/$campaignId/volunteers/roster/'
      preLoaderRoute: typeof CampaignsCampaignIdVolunteersRosterIndexRouteImport
      parentRoute: typeof CampaignsCampaignIdVolunteersRoute
    }
    '/campaigns/$campaignId/volunteers/register/': {
      id: '/campaigns/$campaignId/volunteers/register/'
      path: '/register'
      fullPath: '/campaigns/$campaignId/volunteers/register/'
      preLoaderRoute: typeof CampaignsCampaignIdVolunteersRegisterIndexRouteImport
      parentRoute: typeof CampaignsCampaignIdVolunteersRoute
    }
    '/campaigns/$campaignId/volunteers/$volunteerId/': {
      id: '/campaigns/$campaignId/volunteers/$volunteerId/'
      path: '/$volunteerId'
      fullPath: '/campaigns/$campaignId/volunteers/$volunteerId/'
      preLoaderRoute: typeof CampaignsCampaignIdVolunteersVolunteerIdIndexRouteImport
      parentRoute: typeof CampaignsCampaignIdVolunteersRoute
    }
    '/campaigns/$campaignId/phone-banking/sessions/': {
      id: '/campaigns/$campaignId/phone-banking/sessions/'
      path: '/sessions'
      fullPath: '/campaigns/$campaignId/phone-banking/sessions/'
      preLoaderRoute: typeof CampaignsCampaignIdPhoneBankingSessionsIndexRouteImport
      parentRoute: typeof CampaignsCampaignIdPhoneBankingRoute
    }
    '/campaigns/$campaignId/phone-banking/my-sessions/': {
      id: '/campaigns/$campaignId/phone-banking/my-sessions/'
      path: '/my-sessions'
      fullPath: '/campaigns/$campaignId/phone-banking/my-sessions/'
      preLoaderRoute: typeof CampaignsCampaignIdPhoneBankingMySessionsIndexRouteImport
      parentRoute: typeof CampaignsCampaignIdPhoneBankingRoute
    }
    '/campaigns/$campaignId/phone-banking/dnc/': {
      id: '/campaigns/$campaignId/phone-banking/dnc/'
      path: '/dnc'
      fullPath: '/campaigns/$campaignId/phone-banking/dnc/'
      preLoaderRoute: typeof CampaignsCampaignIdPhoneBankingDncIndexRouteImport
      parentRoute: typeof CampaignsCampaignIdPhoneBankingRoute
    }
    '/campaigns/$campaignId/phone-banking/call-lists/': {
      id: '/campaigns/$campaignId/phone-banking/call-lists/'
      path: '/call-lists'
      fullPath: '/campaigns/$campaignId/phone-banking/call-lists/'
      preLoaderRoute: typeof CampaignsCampaignIdPhoneBankingCallListsIndexRouteImport
      parentRoute: typeof CampaignsCampaignIdPhoneBankingRoute
    }
    '/campaigns/$campaignId/voters/lists/$listId': {
      id: '/campaigns/$campaignId/voters/lists/$listId'
      path: '/lists/$listId'
      fullPath: '/campaigns/$campaignId/voters/lists/$listId'
      preLoaderRoute: typeof CampaignsCampaignIdVotersListsListIdRouteImport
      parentRoute: typeof CampaignsCampaignIdVotersRoute
    }
    '/campaigns/$campaignId/voters/imports/new': {
      id: '/campaigns/$campaignId/voters/imports/new'
      path: '/imports/new'
      fullPath: '/campaigns/$campaignId/voters/imports/new'
      preLoaderRoute: typeof CampaignsCampaignIdVotersImportsNewRouteImport
      parentRoute: typeof CampaignsCampaignIdVotersRoute
    }
    '/campaigns/$campaignId/phone-banking/call-lists/$callListId': {
      id: '/campaigns/$campaignId/phone-banking/call-lists/$callListId'
      path: '/call-lists/$callListId'
      fullPath: '/campaigns/$campaignId/phone-banking/call-lists/$callListId'
      preLoaderRoute: typeof CampaignsCampaignIdPhoneBankingCallListsCallListIdRouteImport
      parentRoute: typeof CampaignsCampaignIdPhoneBankingRoute
    }
    '/campaigns/$campaignId/canvassing/walk-lists/$walkListId': {
      id: '/campaigns/$campaignId/canvassing/walk-lists/$walkListId'
      path: '/walk-lists/$walkListId'
      fullPath: '/campaigns/$campaignId/canvassing/walk-lists/$walkListId'
      preLoaderRoute: typeof CampaignsCampaignIdCanvassingWalkListsWalkListIdRouteImport
      parentRoute: typeof CampaignsCampaignIdCanvassingRoute
    }
    '/campaigns/$campaignId/canvassing/turfs/new': {
      id: '/campaigns/$campaignId/canvassing/turfs/new'
      path: '/turfs/new'
      fullPath: '/campaigns/$campaignId/canvassing/turfs/new'
      preLoaderRoute: typeof CampaignsCampaignIdCanvassingTurfsNewRouteImport
      parentRoute: typeof CampaignsCampaignIdCanvassingRoute
    }
    '/campaigns/$campaignId/canvassing/turfs/$turfId': {
      id: '/campaigns/$campaignId/canvassing/turfs/$turfId'
      path: '/turfs/$turfId'
      fullPath: '/campaigns/$campaignId/canvassing/turfs/$turfId'
      preLoaderRoute: typeof CampaignsCampaignIdCanvassingTurfsTurfIdRouteImport
      parentRoute: typeof CampaignsCampaignIdCanvassingRoute
    }
    '/campaigns/$campaignId/volunteers/shifts/$shiftId/': {
      id: '/campaigns/$campaignId/volunteers/shifts/$shiftId/'
      path: '/shifts/$shiftId'
      fullPath: '/campaigns/$campaignId/volunteers/shifts/$shiftId/'
      preLoaderRoute: typeof CampaignsCampaignIdVolunteersShiftsShiftIdIndexRouteImport
      parentRoute: typeof CampaignsCampaignIdVolunteersRoute
    }
    '/campaigns/$campaignId/phone-banking/sessions/$sessionId/': {
      id: '/campaigns/$campaignId/phone-banking/sessions/$sessionId/'
      path: '/sessions/$sessionId'
      fullPath: '/campaigns/$campaignId/phone-banking/sessions/$sessionId/'
      preLoaderRoute: typeof CampaignsCampaignIdPhoneBankingSessionsSessionIdIndexRouteImport
      parentRoute: typeof CampaignsCampaignIdPhoneBankingRoute
    }
    '/campaigns/$campaignId/phone-banking/sessions/$sessionId/call': {
      id: '/campaigns/$campaignId/phone-banking/sessions/$sessionId/call'
      path: '/sessions/$sessionId/call'
      fullPath: '/campaigns/$campaignId/phone-banking/sessions/$sessionId/call'
      preLoaderRoute: typeof CampaignsCampaignIdPhoneBankingSessionsSessionIdCallRouteImport
      parentRoute: typeof CampaignsCampaignIdPhoneBankingRoute
    }
  }
}

interface CampaignsCampaignIdCanvassingRouteChildren {
  CampaignsCampaignIdCanvassingIndexRoute: typeof CampaignsCampaignIdCanvassingIndexRoute
  CampaignsCampaignIdCanvassingTurfsTurfIdRoute: typeof CampaignsCampaignIdCanvassingTurfsTurfIdRoute
  CampaignsCampaignIdCanvassingTurfsNewRoute: typeof CampaignsCampaignIdCanvassingTurfsNewRoute
  CampaignsCampaignIdCanvassingWalkListsWalkListIdRoute: typeof CampaignsCampaignIdCanvassingWalkListsWalkListIdRoute
}

const CampaignsCampaignIdCanvassingRouteChildren: CampaignsCampaignIdCanvassingRouteChildren =
  {
    CampaignsCampaignIdCanvassingIndexRoute:
      CampaignsCampaignIdCanvassingIndexRoute,
    CampaignsCampaignIdCanvassingTurfsTurfIdRoute:
      CampaignsCampaignIdCanvassingTurfsTurfIdRoute,
    CampaignsCampaignIdCanvassingTurfsNewRoute:
      CampaignsCampaignIdCanvassingTurfsNewRoute,
    CampaignsCampaignIdCanvassingWalkListsWalkListIdRoute:
      CampaignsCampaignIdCanvassingWalkListsWalkListIdRoute,
  }

const CampaignsCampaignIdCanvassingRouteWithChildren =
  CampaignsCampaignIdCanvassingRoute._addFileChildren(
    CampaignsCampaignIdCanvassingRouteChildren,
  )

interface CampaignsCampaignIdPhoneBankingRouteChildren {
  CampaignsCampaignIdPhoneBankingMessagesRoute: typeof CampaignsCampaignIdPhoneBankingMessagesRoute
  CampaignsCampaignIdPhoneBankingIndexRoute: typeof CampaignsCampaignIdPhoneBankingIndexRoute
  CampaignsCampaignIdPhoneBankingCallListsCallListIdRoute: typeof CampaignsCampaignIdPhoneBankingCallListsCallListIdRoute
  CampaignsCampaignIdPhoneBankingCallListsIndexRoute: typeof CampaignsCampaignIdPhoneBankingCallListsIndexRoute
  CampaignsCampaignIdPhoneBankingDncIndexRoute: typeof CampaignsCampaignIdPhoneBankingDncIndexRoute
  CampaignsCampaignIdPhoneBankingMySessionsIndexRoute: typeof CampaignsCampaignIdPhoneBankingMySessionsIndexRoute
  CampaignsCampaignIdPhoneBankingSessionsIndexRoute: typeof CampaignsCampaignIdPhoneBankingSessionsIndexRoute
  CampaignsCampaignIdPhoneBankingSessionsSessionIdCallRoute: typeof CampaignsCampaignIdPhoneBankingSessionsSessionIdCallRoute
  CampaignsCampaignIdPhoneBankingSessionsSessionIdIndexRoute: typeof CampaignsCampaignIdPhoneBankingSessionsSessionIdIndexRoute
}

const CampaignsCampaignIdPhoneBankingRouteChildren: CampaignsCampaignIdPhoneBankingRouteChildren =
  {
    CampaignsCampaignIdPhoneBankingMessagesRoute:
      CampaignsCampaignIdPhoneBankingMessagesRoute,
    CampaignsCampaignIdPhoneBankingIndexRoute:
      CampaignsCampaignIdPhoneBankingIndexRoute,
    CampaignsCampaignIdPhoneBankingCallListsCallListIdRoute:
      CampaignsCampaignIdPhoneBankingCallListsCallListIdRoute,
    CampaignsCampaignIdPhoneBankingCallListsIndexRoute:
      CampaignsCampaignIdPhoneBankingCallListsIndexRoute,
    CampaignsCampaignIdPhoneBankingDncIndexRoute:
      CampaignsCampaignIdPhoneBankingDncIndexRoute,
    CampaignsCampaignIdPhoneBankingMySessionsIndexRoute:
      CampaignsCampaignIdPhoneBankingMySessionsIndexRoute,
    CampaignsCampaignIdPhoneBankingSessionsIndexRoute:
      CampaignsCampaignIdPhoneBankingSessionsIndexRoute,
    CampaignsCampaignIdPhoneBankingSessionsSessionIdCallRoute:
      CampaignsCampaignIdPhoneBankingSessionsSessionIdCallRoute,
    CampaignsCampaignIdPhoneBankingSessionsSessionIdIndexRoute:
      CampaignsCampaignIdPhoneBankingSessionsSessionIdIndexRoute,
  }

const CampaignsCampaignIdPhoneBankingRouteWithChildren =
  CampaignsCampaignIdPhoneBankingRoute._addFileChildren(
    CampaignsCampaignIdPhoneBankingRouteChildren,
  )

interface CampaignsCampaignIdSettingsRouteChildren {
  CampaignsCampaignIdSettingsDangerRoute: typeof CampaignsCampaignIdSettingsDangerRoute
  CampaignsCampaignIdSettingsGeneralRoute: typeof CampaignsCampaignIdSettingsGeneralRoute
  CampaignsCampaignIdSettingsMembersRoute: typeof CampaignsCampaignIdSettingsMembersRoute
  CampaignsCampaignIdSettingsIndexRoute: typeof CampaignsCampaignIdSettingsIndexRoute
}

const CampaignsCampaignIdSettingsRouteChildren: CampaignsCampaignIdSettingsRouteChildren =
  {
    CampaignsCampaignIdSettingsDangerRoute:
      CampaignsCampaignIdSettingsDangerRoute,
    CampaignsCampaignIdSettingsGeneralRoute:
      CampaignsCampaignIdSettingsGeneralRoute,
    CampaignsCampaignIdSettingsMembersRoute:
      CampaignsCampaignIdSettingsMembersRoute,
    CampaignsCampaignIdSettingsIndexRoute:
      CampaignsCampaignIdSettingsIndexRoute,
  }

const CampaignsCampaignIdSettingsRouteWithChildren =
  CampaignsCampaignIdSettingsRoute._addFileChildren(
    CampaignsCampaignIdSettingsRouteChildren,
  )

interface CampaignsCampaignIdSurveysRouteChildren {
  CampaignsCampaignIdSurveysScriptIdRoute: typeof CampaignsCampaignIdSurveysScriptIdRoute
  CampaignsCampaignIdSurveysIndexRoute: typeof CampaignsCampaignIdSurveysIndexRoute
}

const CampaignsCampaignIdSurveysRouteChildren: CampaignsCampaignIdSurveysRouteChildren =
  {
    CampaignsCampaignIdSurveysScriptIdRoute:
      CampaignsCampaignIdSurveysScriptIdRoute,
    CampaignsCampaignIdSurveysIndexRoute: CampaignsCampaignIdSurveysIndexRoute,
  }

const CampaignsCampaignIdSurveysRouteWithChildren =
  CampaignsCampaignIdSurveysRoute._addFileChildren(
    CampaignsCampaignIdSurveysRouteChildren,
  )

interface CampaignsCampaignIdVolunteersRouteChildren {
  CampaignsCampaignIdVolunteersIndexRoute: typeof CampaignsCampaignIdVolunteersIndexRoute
  CampaignsCampaignIdVolunteersVolunteerIdIndexRoute: typeof CampaignsCampaignIdVolunteersVolunteerIdIndexRoute
  CampaignsCampaignIdVolunteersRegisterIndexRoute: typeof CampaignsCampaignIdVolunteersRegisterIndexRoute
  CampaignsCampaignIdVolunteersRosterIndexRoute: typeof CampaignsCampaignIdVolunteersRosterIndexRoute
  CampaignsCampaignIdVolunteersShiftsIndexRoute: typeof CampaignsCampaignIdVolunteersShiftsIndexRoute
  CampaignsCampaignIdVolunteersTagsIndexRoute: typeof CampaignsCampaignIdVolunteersTagsIndexRoute
  CampaignsCampaignIdVolunteersShiftsShiftIdIndexRoute: typeof CampaignsCampaignIdVolunteersShiftsShiftIdIndexRoute
}

const CampaignsCampaignIdVolunteersRouteChildren: CampaignsCampaignIdVolunteersRouteChildren =
  {
    CampaignsCampaignIdVolunteersIndexRoute:
      CampaignsCampaignIdVolunteersIndexRoute,
    CampaignsCampaignIdVolunteersVolunteerIdIndexRoute:
      CampaignsCampaignIdVolunteersVolunteerIdIndexRoute,
    CampaignsCampaignIdVolunteersRegisterIndexRoute:
      CampaignsCampaignIdVolunteersRegisterIndexRoute,
    CampaignsCampaignIdVolunteersRosterIndexRoute:
      CampaignsCampaignIdVolunteersRosterIndexRoute,
    CampaignsCampaignIdVolunteersShiftsIndexRoute:
      CampaignsCampaignIdVolunteersShiftsIndexRoute,
    CampaignsCampaignIdVolunteersTagsIndexRoute:
      CampaignsCampaignIdVolunteersTagsIndexRoute,
    CampaignsCampaignIdVolunteersShiftsShiftIdIndexRoute:
      CampaignsCampaignIdVolunteersShiftsShiftIdIndexRoute,
  }

const CampaignsCampaignIdVolunteersRouteWithChildren =
  CampaignsCampaignIdVolunteersRoute._addFileChildren(
    CampaignsCampaignIdVolunteersRouteChildren,
  )

interface CampaignsCampaignIdVotersRouteChildren {
  CampaignsCampaignIdVotersVoterIdRoute: typeof CampaignsCampaignIdVotersVoterIdRoute
  CampaignsCampaignIdVotersIndexRoute: typeof CampaignsCampaignIdVotersIndexRoute
  CampaignsCampaignIdVotersImportsNewRoute: typeof CampaignsCampaignIdVotersImportsNewRoute
  CampaignsCampaignIdVotersListsListIdRoute: typeof CampaignsCampaignIdVotersListsListIdRoute
  CampaignsCampaignIdVotersImportsIndexRoute: typeof CampaignsCampaignIdVotersImportsIndexRoute
  CampaignsCampaignIdVotersListsIndexRoute: typeof CampaignsCampaignIdVotersListsIndexRoute
  CampaignsCampaignIdVotersTagsIndexRoute: typeof CampaignsCampaignIdVotersTagsIndexRoute
}

const CampaignsCampaignIdVotersRouteChildren: CampaignsCampaignIdVotersRouteChildren =
  {
    CampaignsCampaignIdVotersVoterIdRoute:
      CampaignsCampaignIdVotersVoterIdRoute,
    CampaignsCampaignIdVotersIndexRoute: CampaignsCampaignIdVotersIndexRoute,
    CampaignsCampaignIdVotersImportsNewRoute:
      CampaignsCampaignIdVotersImportsNewRoute,
    CampaignsCampaignIdVotersListsListIdRoute:
      CampaignsCampaignIdVotersListsListIdRoute,
    CampaignsCampaignIdVotersImportsIndexRoute:
      CampaignsCampaignIdVotersImportsIndexRoute,
    CampaignsCampaignIdVotersListsIndexRoute:
      CampaignsCampaignIdVotersListsIndexRoute,
    CampaignsCampaignIdVotersTagsIndexRoute:
      CampaignsCampaignIdVotersTagsIndexRoute,
  }

const CampaignsCampaignIdVotersRouteWithChildren =
  CampaignsCampaignIdVotersRoute._addFileChildren(
    CampaignsCampaignIdVotersRouteChildren,
  )

interface CampaignsCampaignIdRouteChildren {
  CampaignsCampaignIdCanvassingRoute: typeof CampaignsCampaignIdCanvassingRouteWithChildren
  CampaignsCampaignIdDashboardRoute: typeof CampaignsCampaignIdDashboardRoute
  CampaignsCampaignIdPhoneBankingRoute: typeof CampaignsCampaignIdPhoneBankingRouteWithChildren
  CampaignsCampaignIdSettingsRoute: typeof CampaignsCampaignIdSettingsRouteWithChildren
  CampaignsCampaignIdSurveysRoute: typeof CampaignsCampaignIdSurveysRouteWithChildren
  CampaignsCampaignIdVolunteersRoute: typeof CampaignsCampaignIdVolunteersRouteWithChildren
  CampaignsCampaignIdVotersRoute: typeof CampaignsCampaignIdVotersRouteWithChildren
}

const CampaignsCampaignIdRouteChildren: CampaignsCampaignIdRouteChildren = {
  CampaignsCampaignIdCanvassingRoute:
    CampaignsCampaignIdCanvassingRouteWithChildren,
  CampaignsCampaignIdDashboardRoute: CampaignsCampaignIdDashboardRoute,
  CampaignsCampaignIdPhoneBankingRoute:
    CampaignsCampaignIdPhoneBankingRouteWithChildren,
  CampaignsCampaignIdSettingsRoute:
    CampaignsCampaignIdSettingsRouteWithChildren,
  CampaignsCampaignIdSurveysRoute: CampaignsCampaignIdSurveysRouteWithChildren,
  CampaignsCampaignIdVolunteersRoute:
    CampaignsCampaignIdVolunteersRouteWithChildren,
  CampaignsCampaignIdVotersRoute: CampaignsCampaignIdVotersRouteWithChildren,
}

const CampaignsCampaignIdRouteWithChildren =
  CampaignsCampaignIdRoute._addFileChildren(CampaignsCampaignIdRouteChildren)

interface FieldCampaignIdRouteChildren {
  FieldCampaignIdCanvassingRoute: typeof FieldCampaignIdCanvassingRoute
  FieldCampaignIdPhoneBankingRoute: typeof FieldCampaignIdPhoneBankingRoute
  FieldCampaignIdIndexRoute: typeof FieldCampaignIdIndexRoute
}

const FieldCampaignIdRouteChildren: FieldCampaignIdRouteChildren = {
  FieldCampaignIdCanvassingRoute: FieldCampaignIdCanvassingRoute,
  FieldCampaignIdPhoneBankingRoute: FieldCampaignIdPhoneBankingRoute,
  FieldCampaignIdIndexRoute: FieldCampaignIdIndexRoute,
}

const FieldCampaignIdRouteWithChildren = FieldCampaignIdRoute._addFileChildren(
  FieldCampaignIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CallbackRoute: CallbackRoute,
  LoginRoute: LoginRoute,
  CampaignsCampaignIdRoute: CampaignsCampaignIdRouteWithChildren,
  CampaignsNewRoute: CampaignsNewRoute,
  FieldCampaignIdRoute: FieldCampaignIdRouteWithChildren,
  OrgMembersRoute: OrgMembersRoute,
  OrgSettingsRoute: OrgSettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
